- CHANGELOG.md
- labelbox/schema/dataset.py
- tests/integration/test_data_rows.py
Fix for issue https://github.com/Labelbox/labelbox-python/issues/16.
> Fix Dataset.create_data_row local file upload

- .gitignore
- labelbox/pagination.py
- labelbox/schema/data_row.py
- tests/integration/test_asset_metadata.py
https://labelbox.atlassian.net/browse/BACKEND-957
> [BACKEND-957] MetadataType -> AttachmentType

- .gitignore
- CHANGELOG.md
- Makefile
- labelbox/schema/data_row.py
- setup.py
- tests/integration/test_asset_metadata.py
* fix failing `create_metadata` calls
> v2.4.6 fix `create_metadata`

- labelbox/pagination.py
> Initialize index in PaginatedCollection in constructor

- tests/integration/test_data_rows.py
test coverage for https://github.com/Labelbox/labelbox-python/pull/75
> test coverage

- .github/workflows/python-package.yml
- labelbox/schema/project.py
- tests/integration/test_toggle_mal.py
* Fix GitHub action env var handling
* Fix yapf compliance
Tests still fail. This should be addressed, but is a larger issue unrelated to the fixes in this PR.
> Fix build GitHub action

- labelbox/client.py
Error messages coming from the api were slightly changed. This update properly parses the new format.
> catches errors properly

- examples/basics/ontologies.ipynb
Added missing ontology demo notebook.
> add ontology example

- labelbox/schema/project.py
- tests/integration/test_issues.py
https://labelbox.atlassian.net/browse/PLAT-1233
Blocked on: 
https://github.com/Labelbox/intelligence/pull/4063
All Issues
```
from labelbox import Client
client = Client(api_key='SOME KEY', endpoint='http://localhost:8080/graphql')
p = client.get_project('ckml5cezy009h0871u12kogd6')
p.export_issues()
Output: 'http://localhost:8080/v1/project/ckml5cezy009h0871u12kogd6/issues?bewit=bGFiZWxib3gtYXBpXDE2MTczOTg4MzdceWt4UWswUENBL0JPeXhCNVh4QldLdncvR3NyNVpqYm11YjlDU1kyZHZkTT1c'
```
Open Issues
```
client.get_project('ckml5cezy009h0871u12kogd6')
export_issues("Open")
Output: 'http://localhost:8080/v1/project/ckml5cezy009h0871u12kogd6/issues?status=Open&bewit=bGFiZWxib3gtYXBpXDE2MTczOTg4NDVcbUhLY0ZsU0tzKzMvWXZxT0hMQ3dtL3IyUzZvMHpSMmZyQ3JIRXNjT3VBdz1c'
```
Resolved Issues
``` …
```
> Add Export Issues to SDK

- labelbox/schema/bulk_import_request.py
- labelbox/schema/project.py
- tests/integration/conftest.py
- tests/integration/test_project.py
* Allow users to fetch all data rows for a given project with a single bulk operation.
> [DIAG-101] bulk export queued data rows

- labelbox/schema/bulk_import_request.py
- tests/integration/bulk_import/test_ndjson_validation.py
Remove data row validation from client side mal validation. This will speed up validation for projects with a lot of data rows .
> remove data row validation

- labelbox/__init__.py
- labelbox/client.py
- labelbox/schema/__init__.py
- labelbox/schema/model.py
- labelbox/schema/model_run.py
https://labelbox.atlassian.net/browse/DIAG-196
> [DIAG-196] model-run entity

- labelbox/data/metrics/iou.py
- labelbox/data/metrics/preprocess.py
- tests/data/metrics/conftest.py
- tests/data/metrics/test_iou.py
iou metric supports multi-class seg masks
> mult-class seg iou

- labelbox/schema/ontology.py
Fixes the problems outlined here: https://github.com/Labelbox/labelbox-python/issues/191
> support extending ontology objects

- labelbox/client.py
- labelbox/schema/dataset.py
* Use threadpoolexecutor for `dataset.create_data_rows` so that upload is compatible with aws lambda functions.
* Add retry logic to `client.upload_data`
> improve create data rows

- examples/model_assisted_labeling/image_mea.ipynb
- labelbox/data/annotation_types/__init__.py
- labelbox/data/annotation_types/data/raster.py
- labelbox/data/annotation_types/label.py
- labelbox/data/annotation_types/metrics.py
- labelbox/data/serialization/labelbox_v1/converter.py
- labelbox/data/serialization/labelbox_v1/label.py
- labelbox/data/serialization/ndjson/classification.py
- labelbox/data/serialization/ndjson/label.py
- labelbox/data/serialization/ndjson/metric.py
- labelbox/schema/model.py
- tests/data/annotation_types/test_metrics.py
- tests/data/assets/ndjson/metric_import.json
- tests/data/serialization/ndjson/test_metric.py
- tests/integration/conftest.py
- tests/integration/test_model.py
- tests/integration/test_model_run.py
* Fix MEA bugs / tests
* Add metric type and change converter classes to support metric annotations
* Update mea notebook
> annotation metric type and demo

- labelbox/data/generator.py
Threadpoolexecutor and locks don't play well together.
> fix deadlock

- labelbox/schema/asset_attachment.py
* Adding "HTML" as a valid attachment type
* Related PR: https://github.com/Labelbox/intelligence/pull/5405
> [CCV-214] Render IAM DA text assets in the attachments panel

- labelbox/data/annotation_types/metrics/scalar.py
- labelbox/data/serialization/ndjson/label.py
- labelbox/data/serialization/ndjson/metric.py
- tests/data/assets/ndjson/custom_confusion_matrix_import.json
- tests/data/assets/ndjson/custom_scalar_import.json
- tests/data/serialization/ndjson/test_metric.py
serialize confidence and confusion matrix metrics for upload.
> Metric serialization

- labelbox/data/annotation_types/annotation.py
- labelbox/data/annotation_types/data/raster.py
- labelbox/data/annotation_types/geometry/geometry.py
- labelbox/data/annotation_types/geometry/line.py
- labelbox/data/annotation_types/geometry/mask.py
- labelbox/data/annotation_types/geometry/point.py
- labelbox/data/annotation_types/geometry/polygon.py
- labelbox/data/annotation_types/geometry/rectangle.py
- labelbox/data/annotation_types/label.py
- labelbox/data/serialization/labelbox_v1/classification.py
- labelbox/data/serialization/labelbox_v1/objects.py
* Add docstring examples of annotation types and a few helper methods
* Allow color to be a single integer
* Allow users to pass int arrays to RasterData and attempt coercion to uint8
> Annotation type documentation 

- examples/integrations/detectron2/coco_object.ipynb
- examples/model_diagnostics/custom_metrics_demo.ipynb
- examples/model_diagnostics/model_diagnostics_demo.ipynb
- examples/model_diagnostics/model_diagnostics_guide.ipynb
- labelbox/schema/model_run.py
- tests/integration/annotation_import/conftest.py
- tests/integration/annotation_import/test_mea_prediction_import.py
- tests/integration/annotation_import/test_model_run.py
* Rename AnnotationGroup to ModelRunDataRows
* I made these changes backwards compatible and added a deprecation warning.
> remove annotation groups

- labelbox/schema/bulk_import_request.py
- tests/integration/annotation_import/conftest.py
- tests/integration/annotation_import/test_ndjson_validation.py
- tests/integration/test_labeling_frontend.py
Update mal validation to be compatible with new in line mask types.
> in-line validation

- examples/model_assisted_labeling/video_mal.ipynb
Provide notebook for the launch of video mal
> ADD video mal notebook

- examples/integrations/gcp/docker-compose.yaml
- examples/integrations/gcp/src/coordinator/coordinator.py
- examples/integrations/gcp/src/coordinator/etl/images/bounding_box_etl.py
- examples/integrations/gcp/src/coordinator/etl/images/classification_etl.py
- examples/integrations/gcp/src/coordinator/etl/text/classification_etl.py
- examples/integrations/gcp/src/coordinator/pipelines.py
- examples/integrations/gcp/src/coordinator/training/images/classification_training.py
- examples/integrations/gcp/src/coordinator/training/text/classification_training.py
- examples/integrations/gcp/src/jobs/etl/images/classification/Dockerfile
- examples/integrations/gcp/src/jobs/etl/images/classification/classification_etl.py
- examples/integrations/gcp/src/jobs/etl/images/classification/requirements.txt
- examples/integrations/gcp/src/jobs/etl/text/classification/Dockerfile
- examples/integrations/gcp/src/jobs/etl/text/classification/classification_etl.py
- examples/integrations/gcp/src/jobs/etl/text/classification/requirements.txt
- examples/integrations/gcp/src/jobs/etl/text/ner/ner_etl.py
- examples/integrations/gcp/test/seed/seed_image_classification.py
- examples/integrations/gcp/test/seed/seed_image_multi_classification.py
- examples/integrations/gcp/test/seed/seed_image_single_classification.py
- examples/integrations/gcp/test/seed/seed_text_classification.py
- examples/integrations/gcp/test/seed/seed_text_multi_classification.py
- examples/integrations/gcp/test/test_image_classification.py
- examples/integrations/gcp/test/test_image_multi_classification.py
- examples/integrations/gcp/test/test_text_classification.py
- examples/integrations/gcp/test/test_text_multi_classification.py
* Add seed script for testing
* Add ETL logic
* Update coordinator to run etl and train classification models for text and image data.
> classification etl / training

- labelbox/client.py
remove imports that require annotation type dependencies
> import fix

- examples/model_diagnostics/model_diagnostics_demo.ipynb
[JIRA TICKET](https://labelbox.atlassian.net/browse/AL-1473)
https://github.com/Labelbox/intelligence/pull/7290
This example is going to be referenced by the UI within the application:
> [AL-1473] Add export labels example

- labelbox/data/annotation_types/data/tiled_image.py
https://labelbox.atlassian.net/browse/AL-1701
> [AL-1701] Removal of Logger Level

- examples/basics/datasets.ipynb
- examples/basics/projects.ipynb
cut out duplicate cells, fixed dataset to new_dataset in create section so user can easily see where the created data row lands
> made minor fixes to two notebooks

- examples/README.md
- examples/annotation_import/basics.ipynb
- examples/annotation_import/text.ipynb
- examples/annotation_import/tiled.ipynb
Readme
- Removed debugging MAL row
- Renamed to Annotation Import
- Retained MAL title for Video and Subclasses, since I didn’t change those
- Re-routed all the links to the annotation_import folder
basics.ipynb - updated the Colab Link to align with the folder structure
- Note - when clicking on the Colab link, the title of the file is mal_basics.ipynb instead of basics.ipynb
Image.ipynb - updated the Colab Link to align with the folder structure
text.ipynb - updated the Colab Link to align with the folder structure
- Note - when clicking on the Colab link, the title of the file is text_mal.ipynb instead of text.ipynb
tiled.ipynb - updated the Colab Link to align with the folder structure, updated the title of the document (code cell 3)
> Updated Readme and Colab Links in Tutorials

- examples/annotation_import/basics.ipynb
- examples/annotation_import/image.ipynb
- examples/annotation_import/text.ipynb
- examples/annotation_import/tiled.ipynb
- examples/basics/labels.ipynb
- examples/label_export/text.ipynb
- examples/label_export/video.ipynb
Fixing hyperlink urls in the notebooks
> Notebooks - Update Url to Hyperlink

- examples/integrations/gcp/custom_example/batch_predictions/batch_prediction.py
I ended up having to hard code more than the model run uid. I needed the ontology and didn't know how to get that without the project, and not sure how to get the model run object without the model id either.
The etl file name might be another issue, not sure we are tracking/saving that somewhere.
> prototype batch predictions for image classifier

- examples/integrations/gcp/src/jobs/etl/images/bounding_box/bounding_box_etl.py
- examples/integrations/gcp/src/jobs/etl/images/classification/classification_etl.py
- examples/integrations/gcp/test/seed/assign_partition.py
* Partition the dataset based on the split specified in the export
> image partition

- examples/integrations/gcp/src/jobs/etl/text/classification/classification_etl.py
- examples/integrations/gcp/src/jobs/etl/text/ner/ner_etl.py
Basically a mirror of what @msokoloff1 did with the image etl
> use real splits

- CHANGELOG.md
- labelbox/__init__.py
> [3.16.0] Changelog

- examples/integrations/gcp/test/seed/seed_bbox.py
small fix to the bbox seed script
> small fix to bbox seed script

- CHANGELOG.md
Correction to the changelog for the ability to delete an attachment
> update to the changelog

- labelbox/data/metrics/confusion_matrix/calculation.py
- labelbox/data/metrics/iou/calculation.py
- tests/data/metrics/confusion_matrix/conftest.py
- tests/data/metrics/confusion_matrix/test_confusion_matrix_data_row.py
- tests/data/metrics/confusion_matrix/test_confusion_matrix_feature.py
- tests/data/metrics/iou/data_row/conftest.py
- tests/data/metrics/iou/data_row/test_data_row_iou.py
https://labelbox.atlassian.net/browse/AL-1723
Addition of confusion matrix logic for NER/ TextEntity annotations
> [AL-1723] NER Confusion Matrix

- examples/basics/batches.ipynb
This notebook contains useful SDK functions ​to create and use batches through the Python SDK. 
This is should be used with customers wanting to get started with collecting Datarows into Batches through the SDK. 
The information in this notebook comes from the [Batches page in the docs](https://docs.labelbox.com/docs/batches)
> Created Batches notebook.

- examples/integrations/gcp/deployment/deploy.sh
- examples/integrations/gcp/src/coordinator/coordinator.py
- examples/integrations/gcp/src/coordinator/pipelines/images/bounding_box.py
- examples/integrations/gcp/src/coordinator/pipelines/images/classification.py
- examples/integrations/gcp/src/coordinator/pipelines/text/classification.py
- examples/integrations/gcp/src/coordinator/pipelines/text/ner.py
- examples/integrations/gcp/src/coordinator/pipelines/types.py
- examples/integrations/gcp/src/jobs/etl/images/bounding_box/bounding_box_etl.py
- examples/integrations/gcp/src/jobs/etl/images/classification/classification_etl.py
- examples/integrations/gcp/src/jobs/etl/text/classification/classification_etl.py
- examples/integrations/gcp/src/jobs/etl/text/ner/ner_etl.py
> use sdk functions

- examples/basics/data_rows.ipynb
- examples/basics/ontologies.ipynb
- examples/label_export/text.ipynb
- examples/label_export/video.ipynb
- edited data rows colab to include all the data types we offered
- displayed the required tool names in a table in the ontologies colab
- displayed appropriate outputs for the text and video export colabs I uploaded earlier this week
> colab edits and show cell outputs

- examples/README.md
- examples/basics/batches.ipynb
- I corrected Colab and github links in notebook to point to the correct places in google Colab and the right directory in github repo. 
- I added the Notebook to the readme with all the examples so that it could be referenced.
> Added Batches Notebook to basics/readme.md + corrected links in Batch Notebook.

- labelbox/schema/ontology.py
New tool type in Ontology to support Raster-Segmentation. Can successfully pull from an existing project's ontology with the new type as well as import the new type into a project's ontology.
> [AL-1908] Raster-Segmentation for Video/Dicom

- labelbox/schema/ontology.py
- tests/unit/test_unit_ontology.py
update to ontology classifications.asdict to not include scope if it is a subclass
> [AL-2296] Remove Scope key when turning Nested Classification to dict

- CHANGELOG.md
Add temporary updates to the changelog file.
> Update changelog for AL-2183 - MediaType support

- e2e_tests_codefresh_pipeline.yaml
yaml file for the e2e pipeline tests
> [AL-2320] E2E Tests

- tests/integration/test_labeling_parameter_overrides.py
Context: https://labelbox.slack.com/archives/C01H3HLUDKP/p1652904235778309
> [AL-0] Fix test_labeling_parameter_overrides() in SDK test

- labelbox/data/metrics/confusion_matrix/confusion_matrix.py
* iou is unused for classification metrics. So iou shouldn't be in the name.
> update classification metric name

- examples/model_diagnostics/custom_metrics_basics.ipynb
missing the json lib (will error out at the end when doing a json.dumps()
> Missing lib

- README.md
- labelbox/__init__.py
- labelbox/schema/model_run.py
- tests/integration/annotation_import/test_model_run.py
- tests/integration/conftest.py
allows users to assign data rows to splits in diagnostics
> assign data row split

- labelbox/schema/project.py
https://github.com/Labelbox/labelbox-python/pull/463
> [AL-3044] Deprecate video label generator

- docs/source/conf.py
- docs/source/index.rst
Updates to documentation + version update alongside internal documentation updates.
> [AL-3110] Documentation Updates

- tests/integration/conftest.py
Duplicating the PR https://github.com/Labelbox/labelbox-python/pull/657 but without the print statement since JTSO is out.
> [AL-0] Picsum Alternative - hydak

- pytest.ini
Adding a flag to pytest.ini to track top 100 slowest test cases
> [AL-0] Add durations to pytest.ini

- CHANGELOG.md
- labelbox/__init__.py
* bump version + update changelog
> prep for release

- CHANGELOG.md
- labelbox/__init__.py
> 3.26.0-dev

- CHANGELOG.md
- labelbox/schema/model_run.py
- tests/integration/annotation_import/conftest.py
- tests/integration/annotation_import/test_model_run.py
Adds methods/tests to:
- Update model run config
- Reset model run config
- Fetch model run config
> Update config [AL-3061]

- CHANGELOG.md
- labelbox/schema/model_run.py
- tests/integration/annotation_import/test_model_run.py
- We want to un-nest the return value for get_config
> Modify get_config return value [AL-3352]

- labelbox/schema/dataset.py
- tests/integration/test_data_rows.py
https://labelbox.atlassian.net/browse/AL-3100
> [Al-3100] Added global key support to bulk import

- CONTRIB.md
- examples/basics/batches.ipynb
- examples/basics/getting_started.ipynb
- labelbox/schema/project.py
- labelbox/schema/queue_mode.py
- tests/integration/test_batch.py
- tests/integration/test_project.py
Going forward, projects will not be allowed to change their queueing mode anymore after creation since it creates data inconsistency within the project. This change introduces queue_mode as an optional argument during creation of a project.
> [QQC-486] Introduce ability to specify queue mode during project creation

- docs/source/index.rst
- labelbox/__init__.py
- labelbox/client.py
- labelbox/orm/model.py
- labelbox/schema/slice.py
- Added new `Slice` entity/dbobject
- Added `client.get_slice(id)` to fetch a Slice by ID
- Added `slice.get_data_row_ids()` to fetch data row ids of a Slice
> [AL-3274] Add Slice object and function to export data row IDs by slice

- labelbox_dev/__init__.py
- labelbox_dev/session.py
Prototyping Session object
https://labelbox.atlassian.net/browse/AL-3869
> [AL-3869] Add session to SDK 4

- labelbox/schema/project.py
- tests/integration/test_batch.py
Ran tests & local notebook to confirm this works.
> [X-0] Fix create batch with data row classes

- labelbox/schema/media_type.py
Relies on https://github.com/Labelbox/intelligence/pull/12029 being merged first.
SDK tests ran and passed, test run results are linked in the above PR.
> [AC-829] Add first class HTML support in project creation.

- examples/annotation_import/pdf.ipynb
Notebook used to create this pr : https://colab.research.google.com/drive/1qdxNUj7kyOLDaFaygI5-q5dYFP37louu?usp=sharing#scrollTo=6ffec272
> Paras' updates

- labelbox_dev/__init__.py
- labelbox_dev/data_row.py
- labelbox_dev/dataset.py
- labelbox_dev/entity.py
- labelbox_dev/exceptions.py
- labelbox_dev/session.py
- labelbox_dev/task.py
- labelbox_dev/utils.py
https://labelbox.atlassian.net/browse/AL-4044 - DataRow bulk import
https://labelbox.atlassian.net/browse/AL-3890 - Async Task interface
> [AL-4044] Implement bulk data row import and async task interfaces for SDK4

- labelbox_dev/data_row.py
https://labelbox.atlassian.net/browse/AL-4494.- followup ticket
> support local file as a source of data rows

- examples/annotation_import/conversational.ipynb
This notebook does not work as is since it assumes a default `Dataset` QueueMode, but the default is now `Batch`.  Updated the example uses the `Batch` mode.
> Fix conversational annotation import example notebook

- Makefile
- scripts/ensure_local_setup.sh
Help avoid issue when one of the required service is not running locally
> add local guardian when running sdk tests

- CHANGELOG.md
- docs/source/conf.py
- labelbox/__init__.py
- labelbox/client.py
Intermittent 520 errors were causing file uploads to fail. In this PR all we are doing is retrying these occasional failures.
> retry 520s

- Dockerfile
To address security vulnerabilities
> upgrade python version and debian os version

- labelbox/data/serialization/ndjson/objects.py
- tests/data/assets/ndjson/polyline_import.json
- tests/data/assets/ndjson/polyline_without_confidence_import.json
- tests/data/assets/ndjson/text_entity_import.json
- tests/data/assets/ndjson/text_entity_without_confidence_import.json
- tests/data/serialization/ndjson/test_polyline.py
- tests/data/serialization/ndjson/test_text_entity.py
In this PR we fix missing confidence attribute for Polyline and TextEntity objects, also adding missing tests for these cases
> [AL-000] Fixed missing confidence attribute in NDline and NDTextEntity

- examples/prediction_upload/image_predictions.ipynb
- examples/prediction_upload/text_predictions.ipynb
Added confidence score for Line and TextEntity objects
> [AL-000] Added confidence to notebooks

- labelbox/data/serialization/ndjson/objects.py
- tests/data/serialization/ndjson/test_text_entity.py
Currently confidence is a required argument, which is not correct. We had a test case for this but it wasn't run properly.
This PR fixes both issues
> [AL-000] Fixed confidence for TextEntity

- tests/integration/annotation_import/test_label_import.py
* project without ontology cannot import annotations
> fix annotation import tests

- examples/prediction_upload/video_predictions.ipynb
1. Simplify version of package prediction import 
2. Created method to update schema ids
> Update video predictions imports

- examples/prediction_upload/text_predictions.ipynb
Just so you know, the checklist classification nested annotation does not work with predictions.
> Simplify imports updates - text prediction

- CHANGELOG.md
- labelbox/schema/project.py
- tests/integration/test_export.py
* Filter exports by all activity related to the label
> last activity filter

- examples/annotation_import/conversational.ipynb
- examples/annotation_import/image.ipynb
- examples/annotation_import/pdf.ipynb
- examples/annotation_import/text.ipynb
- examples/annotation_import/tiled.ipynb
- examples/basics/getting_started.ipynb
- examples/integrations/detectron2/coco_object.ipynb
- examples/label_export/text.ipynb
- examples/model_diagnostics/custom_metrics_basics.ipynb
- examples/model_diagnostics/custom_metrics_demo.ipynb
- examples/model_diagnostics/model_diagnostics_demo.ipynb
- examples/model_diagnostics/model_diagnostics_guide.ipynb
- examples/prediction_upload/geospatial_predictions.ipynb
- examples/prediction_upload/html_predictions.ipynb
- examples/prediction_upload/image_predictions.ipynb
- examples/prediction_upload/text_predictions.ipynb
- examples/test_notebooks.py
- tox.ini
Add test suite to check if notebooks run without errors
> [AL-4860] Remove NDJsonConverter from example notebooks

- labelbox/schema/export_params.py
- labelbox/schema/model_run.py
- labelbox/schema/project.py
> fix export v2 interface

- examples/annotation_import/text.ipynb
Removed the signing function on label payload
Update the lb_type for label generation from ImageData to TextData
Added another example of nested class (checklist)
Added media type to ontology
> Updates - annotations and label payload generation -TEXT

- examples/annotation_import/text.ipynb
- examples/basics/custom_embeddings.ipynb
- examples/basics/data_row_metadata.ipynb
1. Removed metadata (on custom_embeddings, data_row_metadata notebooks)
2. Updated text notebook's ontology  [instructrions -> name]
> removed metadata and update ontology in text notebook

- examples/README.md
updated links to Detectron Notebook from main (devops)
> Detectron_broken_links

- examples/integrations/detectron2/coco_object.ipynb
Based on the prediction import the expected project queue set is currently should be dataset (since the model is querying dataset to make prediction on). This would need to be rework for batch(es)
> addind_queue_dataset

- .github/workflows/python-package.yml
- labelbox/schema/project.py
- tests/integration/conftest.py
- tests/integration/test_batch.py
- tests/integration/test_project.py
Depends on: https://github.com/Labelbox/intelligence/pull/13652
> [AL-4867] Create batch using global keys

- CHANGELOG.md
- docs/source/conf.py
- labelbox/__init__.py
- labelbox/schema/project.py
Fixing bug in create_batch and prepping release for 3.40.1
> Fix create batch

- requirements.txt
> Set typeguard version as 2.13.2 to fix tox error

- tests/integration/annotation_import/conftest.py
- Add assertions for label creation in mea tests
- Add check for DR processing
> [AL-0] Make mea tests more reliable

- labelbox/data/annotation_types/annotation.py
- labelbox/data/serialization/ndjson/base.py
- labelbox/data/serialization/ndjson/classification.py
- labelbox/data/serialization/ndjson/converter.py
- tests/data/annotation_types/classification/test_classification.py
- tests/data/serialization/ndjson/test_conversation.py
* Add optional message_id property to ClassificationAnnotation to support message based classifications for conversational text
* Update NDJsonConverter to serialize / deserialize the message_id.
> [AL-5258] Annotation types for message based conversation classifications

- tests/integration/annotation_import/conftest.py
- tests/integration/annotation_import/fixtures/export_v2.py
- tests/integration/annotation_import/fixtures/video_annotations.py
- tests/integration/annotation_import/test_data_types.py
- tests/integration/test_data_rows.py
- tests/integration/test_dataset.py
- tests/utils.py
Stories:
- https://labelbox.atlassian.net/browse/AL-5553
- https://labelbox.atlassian.net/browse/AL-5538
- https://labelbox.atlassian.net/browse/AL-5539
Essentially updating existing fixtures to fix export v2 tests for Conversational, Document and DICOM data
> [AL-5533][AL-5538][AL-5539]Vb/conversational v2 export al 5538

- labelbox/schema/webhook.py
Adding new enum to match GQL spec
> [QQC-1852] Add SDK support for Workflow Webhook

- tests/integration/annotation_import/fixtures/export_v2.py
https://labelbox.atlassian.net/browse/AL-5584
Fix export v2 test to accommodate the changes done as part of above ticket.
> [AL-5584] Fix tests to accommodate ImageLine -> ImagePolyline change

- examples/annotation_import/conversational.ipynb
- examples/prediction_upload/conversational_predictions.ipynb
- examples/prediction_upload/image_predictions.ipynb
- examples/prediction_upload/pdf_predictions.ipynb
- examples/prediction_upload/text_predictions.ipynb
Created a new PDF prediction notebook : https://labelbox.atlassian.net/browse/SN-48
Created a new Convo prediction notebook: https://labelbox.atlassian.net/browse/SN-47
Added nested classifications to conv annotation import 
Small fixes to the image annotation import and text predictions
> [ SN-48, SN-47 ] : Adding new notebooks + small updates 

- examples/README.md
- examples/project_configuration/project_setup.ipynb
1. Removes dataset project setup and added consensus settings to project creation and batch creation [SN-51](https://labelbox.atlassian.net/browse/SN-51)
2. Updated all the links in the both annotation import + prediction, removed sections that have broken notebooks  [SN-52](https://labelbox.atlassian.net/browse/SN-52)
[SN-51]: https://labelbox.atlassian.net/browse/SN-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SN-52]: https://labelbox.atlassian.net/browse/SN-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Latest updates

- labelbox/client.py
Also updated indents for examples to align with rest of the codebase
> Update create_dataset() docstring

- tests/integration/conftest.py
- tests/integration/test_data_rows.py
[TICKET](https://labelbox.atlassian.net/browse/AL-6504)
Fix for when media attribute is not set on data row.
> [AL-6504] - use wait_for_data_row_processing to get updates on data row

- labelbox/schema/media_type.py
- tests/integration/test_project.py
Jira issue: [Can't fetch a list of projects in SDK when a list contains an LLM project](https://labelbox.atlassian.net/browse/PTDT-1552)
How to test:
1. Add an LLM project
2. Run this code
```
projects = client.get_projects()
for project in projects:
print(project.name)
```
3. Check if it works
> [PTDT-1552] Add LLM media types

- tests/integration/test_batch.py
TLDR; A little bit updated  `test_batch.py`. 
- Added negative path tests for batch creation.
- Fixed imports order.
- General clean up/refactoring.
> [E2E-752 ] Added negative path tests for test_batch.py

- CHANGELOG.md
- docs/source/conf.py
- labelbox/__init__.py
> Pre-release PR for 3.52.0

- .github/workflows/release-container.yaml
- .github/workflows/testing-container.yaml
These permissions seem to be interfering with the ability to push artifacts.
> DEVOPS-1626 - Remove overriding of permissions

- tests/integration/export_v2/test_export_video.py
https://labelbox.atlassian.net/browse/SDK-245
> [SDK-245] Fix tests to add content_last_updated_at field

- CHANGELOG.md
- docs/source/conf.py
- docs/source/index.rst
- labelbox/__init__.py
This is a pre-release PR for the new sdk release 3.53
> Vb/prepare 3.53

- labelbox/schema/batch.py
- labelbox/schema/dataset.py
- labelbox/schema/model_run.py
- labelbox/schema/project.py
https://labelbox.atlassian.net/browse/SDK-300
> Update the copy for exports v1 deprecation warning

- examples/project_configuration/project_setup.ipynb
1. Add the new quality_mode parameter on project creation
> Ao quality mode setup

- labelbox/__init__.py
- labelbox/schema/data_row.py
- labelbox/schema/dataset.py
- labelbox/schema/export_task.py
- labelbox/schema/model_run.py
- labelbox/schema/project.py
- labelbox/schema/slice.py
- labelbox/schema/task.py
Added new ExportTask class to handle streaming of exports of arbitrary size.
> [SDK-225] Add new classes/interfaces to support streaming export task results

- labelbox/orm/db_object.py
- labelbox/schema/export_task.py
- Adapted `experimental` decorator to support static methods
- Removed unnecessary argument `task_id` for methods in ExportTask
> [SDK-430] Address export test findings

- .readthedocs.yml
This fixes some issues we're having in our SDK documentation builds.
> [SDK-455] Fix SDK documentation builds

- labelbox/schema/project.py
- tests/integration/test_project.py
Get tags (resource tags) from a project
> Get resource tags from a project

- examples/basics/Export_V1_to_V2_migration_support.ipynb
Documentation around export V2 capabilities
> [SN-104] V1 to V2 migration support 

- examples/basics/ontologies.ipynb
[https://labelbox.atlassian.net/browse/SN-108](url)
Remove superpixel mentions and add raster segmentation in the table
> [SN-108] Remove superpixel

- examples/annotation_import/image.ipynb
- examples/integrations/huggingface/huggingface.ipynb
https://labelbox.atlassian.net/browse/SN-111
Note: 
It seems that a commit was made to "image.ipynb" file without running the pre-commit hooks previously, and these changes have been included in this current pull request (PR).
> [SN-111]Update user prompts for huggingface colab

- labelbox/schema/project.py
- tests/integration/test_project.py
[TICKET](https://labelbox.atlassian.net/browse/QQC-3241)
Remove project.upsert_review_queue() in SDK
Deprecated warning has been added previously:
https://github.com/Labelbox/labelbox-python/pull/1360
https://github.com/Labelbox/labelbox-python/pull/1364
> [QQC-3241] Remove project.upsert_review_queue() in SDK

- labelbox/schema/model.py
- tests/integration/annotation_import/test_send_to_annotate_mea.py
- tests/integration/test_send_to_annotate.py
Fix invalid feature schema mappings that broke these tests after adding validation for the mapping in https://labelbox.atlassian.net/browse/AL-7547
> [AL-0] Fix S2A validation tests

- CHANGELOG.md
- docs/source/conf.py
- labelbox/__init__.py
Prep PR for sdk release 3.63.0
> Update version info and CHANGELOG for release 3.63.0

- CODEOWNERS
Move codeowners to include the entire platform team
> [PLT-0] Update codeowners to platform

- examples/project_configuration/webhooks.ipynb
- labelbox/schema/webhook.py
These topics are deprecated. Users should not be allowed to create new webhooks using them. Existing webhooks behavior won't be changed.
https://labelbox.atlassian.net/browse/PLT-54
> [PLT-54] Remove old webhook topics from SDK

- CHANGELOG.md
- docs/source/conf.py
- labelbox/__init__.py
Prep PR for SDK release 3.64.0
> Update version info and CHANGELOG for release 3.64.0

- .github/workflows/publish.yaml
- .github/workflows/python-package.yml
- .github/workflows/release-container.yaml
- .github/workflows/team-labeler.yml
- .github/workflows/testing-container.yaml
Updating the versions of the GHA that we have running for CI
> DEVOPS-2606 - updating GHA Versions

- CHANGELOG.md
Add notebook changes to changelog as well.
> Add notebooks update to CHANGELOG for release 3.64.0

- examples/basics/projects.ipynb
Add an example showing how to create a tag, add it to a project and list the tags of a project.
> Add example for tags management

- .github/workflows/secrets_scan.yml
Adding in the trufflehog secret scanning capability to review PR deltas for secrets
> DEVOPS-2599 - Adding secret scanning GHA

- examples/basics/projects.ipynb
Simple example for the method `get_label_count()`
> Add example for project.get_label_count()

- labelbox/client.py
Improvements:
- handling all http 500 codes as errors instead of json parsing errors that display html
> [PLT-162] Fix 500 error handling and reporting

- CONTRIB.md
- README.md
initial pr: https://github.com/Labelbox/labelbox-python/pull/1329 + some improvements
GPT took the best parts and made it clear
> improve messaging in contrib

- .github/workflows/python-package.yml
Run tests once things get merged to develop
> [PLT-0] Always run tests on develop

- .github/workflows/python-package.yml
Always save test cache on develop
> [PLT-0] always run save on develop

- .github/workflows/python-package.yml
Did a PR that will result in workflows ignoring changes that are done just in examples we want to speed up the delivery of notebooks
> Removed examples folder from github workflows

- .github/workflows/python-package.yml
- pytest.ini
- setup.py
- tox.ini
Missing strenum dep in the pypi package
> [PLT-0] Add missing dep
