README.md, labelbox/__init__.py, labelbox/exporters/coco_exporter.py, labelbox/exporters/voc_exporter.py
=> [ENG-673] Don't flip up down

labelbox/schema/dataset.py
I added some samples to `dataset.create_data_rows` and `dataset.create_data_row` due to feedback from our support engineers that users are often confused by the documentation for these two. I also cleaned up the language a little bit.
=> add code samples to dataset.py

labelbox/schema/project.py
So, I noticed that project.setup is broken currently - if you run it on a pictor project, the LFO get attached but not normalized. This is fixed by ensuring that the Labeling Frontend is attached to the project before the options are created
Attach Labeling Frontend to Project before creating the Labeling Frontend Options
Tested locally on V4 and Pictor (staging) and had no issues
=> Change Order of operations in project.setup

labelbox/schema/project.py
This was a request from our support team.
=> Add 30 min flag to export_labels.

CHANGELOG.md, labelbox/client.py, labelbox/schema/dataset.py, setup.py
fixes:
https://labelbox.slack.com/archives/C017A1V4XTQ
https://labelbox.blameless.io/incidents/173/events
- local file uploads go thru `client.upload_file`
- `client.upload_file` will guess mimetype and pass along content type for videos (and images)
we call `mimetypes. guess_type` ourselves because `requests.post` [0] will only pass thru a `content_type` if it is specified explicitly.  `RequestField` doesn't call `mimetypes.guess_type` unless it is isntantiated via `from_tuple` rather than thru its `__init__`[1]
[0] https://github.com/psf/requests/blob/8149e9fe54c36951290f198e90d83c8a0498289c/requests/models.py#L141-L166
[1] https://github.com/urllib3/urllib3/blob/ae7f8bbb57e74ffdb327c5e510963a886fa4ed8b/src/urllib3/fields.py#L181
=> [BACKEND-766] upload with content type guess

CHANGELOG.md, labelbox/client.py, labelbox/orm/db_object.py, labelbox/orm/model.py, labelbox/schema/bulk_import_request.py, labelbox/schema/enums.py, mypy.ini, pytest.ini, requirements.txt, setup.py, tests/integration/test_bulk_import_request.py
Changes:
- Added `BulkImportRequest` entity
- Implemented method to create `BulkImportRequest` from python dictionaries
- Implemented method to upload local ndjson file with predictions to Labelbox' object storage
=> Added BulkImportRequest integration

labelbox/schema/prediction.py
https://labelbox.atlassian.net/browse/BACKEND-841
customers have been stumbling upon this through the auto-gen'd sdk docs
=> [BACKEND-841] update docs to clarify legacy predictions

CHANGELOG.md, labelbox/client.py, labelbox/exceptions.py, labelbox/schema/bulk_import_request.py, labelbox/schema/project.py, mypy.ini, setup.py, tests/integration/test_labeling_frontend.py
1. https://labelbox.atlassian.net/browse/BACKEND-946
pass thru api unavailable message
2. https://labelbox.atlassian.net/browse/BACKEND-947
retry capabilities for 502 and prisma failures
3. clean up labeling frontend test so it works on any project with more than 1 editor
4. loosen requirement version
=> [BACKEND-946] [BACKEND-947] [BACKEND-948] pass thru errors, retry, catch bad annotation types

CHANGELOG.md, labelbox/client.py, labelbox/exceptions.py, labelbox/schema/bulk_import_request.py, labelbox/schema/project.py, mypy.ini, setup.py, tests/integration/test_labeling_frontend.py
just created a new master branch so we revert Labelbox/labelbox-python#49 so that we can have a diff with master when we merge
=> Revert "[BACKEND-946] [BACKEND-947] [BACKEND-948] pass thru errors, retry, catch bad annotation types"

.github/workflows/python-package.yml, Dockerfile, Makefile, README.md
1. testing instructions in README
2. Makefile for testing (was quickest and easiest; we should formalize/unify with github actions eventually)
=> [BACKEND-961] readme for testing

.github/workflows/python-package.yml, Makefile, labelbox/schema/project.py, setup.py, tests/integration/conftest.py, tests/integration/test_project_setup.py, tox.ini
1. hit `staging` for most builds and only hit `prod` for merges into `master`
2. bump up python versions to 37, 38
3. fix test
=> modify conftest and github actions and bump python version

README.md
The previous link no longer exists/has been moved.
=> [PLAT-1] Fixes broken API key generation link in readme

README.md
Took me a bit to figure this out since `pip` can be set up with both python 2 and 3
Assuming most devs use macOS locally, this'd be a worthwhile addition to the README imo
=> Add details on pip installation - macOS

labelbox/schema/project.py
Clarified which methods are supported by the Legacy editor vs new Editor.
=> Update docstrings in project.py

labelbox/client.py
Adding sample code to docstrings in client.py.
=> Update docstrings in client.py

setup.py
There are no binaries for python > 3.7, making it difficult to install in docker without gcc.
=> add python_version to backports-datetime-fromisoformat

.github/workflows/python-package.yml, tox.ini
We can't do parallel testing of the PySDK as all of those tests are connecting to the same (staging) API using the same API key. One of the tests we do is the API limit test, which attempts to overload the endpoint to confirm it will start refusing requests. Running a different test in parallel to that is very likely to cause request refusals in that test as well, resulting in a failed test.
Next, a lot of these tests check the server state to validate that PySDK calls resulted in the right changes. I'm not 100% sure that we would get errors on this point if running tests in parallel, but I am also very far from convinced that we won't. Conceptually it is not fine, the tests are NOT isolated.
One of the reasons why it was possible to introduce these potentially destructive changes to the …
=> Remove parallel testing during build

.readthedocs.yml, docs/requirements.txt, docs/source/conf.py
The .readthedocs.yml file is necessary for Readthedocs platform to build and display the sphinx-generated docs. Also added autodoc to requirements.txt.
=> Add .readthedocs.yml

CHANGELOG.md, README.md, examples/README.md, labelbox/__init__.py, labelbox/schema/bulk_import_request.py
* Some extra information from the mal validation process was being added to the upload. This caused mal for subclasses to fail. 
* Bumped the version and updated the changelog so we are ready to release a fix.
* Updated the README to include that the SDK works for python3.6 
* Fixed an incorrect reference to a notebook in the examples README.
=> fixed bugs, ready for release

labelbox/client.py, labelbox/schema/bulk_import_request.py, labelbox/schema/enums.py, tests/integration/bulk_import/test_bulk_import_request.py
* Checking status, error, or inputs to a bulk import request is an annoying process. We have made this easier by making these ndjson properties of the BulkImportRequest.
* There is also some improved documentation related to bulk imports since we are moving that out of docs.labelbox.com and into the api reference (sphinx docs).
=> Easier fetch bulk import ndjson

labelbox/schema/bulk_import_request.py
LabelBox convention about text location is that "end" is the index of the *last* character of the substring (that is not the python convention).
I.e.: `substring = string[v["start"] : v["end"] + 1]`
So, `v["start"] == v["end"]` is a valid case corresponding to a 1-character substring.
=> NDTextEntity: fix "start >= end" test

examples/basics/data_rows.ipynb, labelbox/orm/db_object.py, labelbox/orm/model.py, labelbox/schema/__init__.py, labelbox/schema/asset_attachment.py, labelbox/schema/asset_metadata.py, labelbox/schema/data_row.py, labelbox/schema/organization.py, tests/integration/test_asset_metadata.py
Changes
* Create new AssetAttachment object to replace AssetMetadata
* Replace create_metadata with create_attachments
* Use new attachment queries and mutations
* Add deprecation warnings - the sdk now supports deprecation warnings on relationships
* Update tests and example notebook to use attachments instead of metadata.
=> metadata to attachment

labelbox/schema/labeling_frontend.py, tests/integration/test_labeling_frontend.py
Builds on https://github.com/Labelbox/intelligence/pull/5010 to remove all `labelingFrontends.projects` references from the SDK + tests
=> [WORK-1] remove labelingFrontend.projects from SDK

labelbox/schema/project.py
This is unused since org is determined by the api key. We want to eventually remove this from the mutation and this is the start.
=> remove org from lfo creation

labelbox/data/serialization/labelbox_v1/label.py
I changed the type for benchmark_id to prevent the following error from happening, following a call to `project.label_genetors()`
`"Unexpected exception while filling the queue. ValidationError(model='LBV1Label', errors=[{'loc': ('Benchmark ID',), 'msg': 'value is not a valid float', 'type': 'type_error.float'}])"`
The error was originally mentioned in ticket  https://labelbox.atlassian.net/browse/LS-797.
=> Change benchmark_id typing to str for LBV1Label

labelbox/data/annotation_types/geometry/geometry.py
If an array is non-contiguous then opencv drawing functions return opencv matrix objects instead of numpy arrays. Adding np.ascontiguous array prevents this situation from occuring. It also doesn't do anything unless the array is non-contiguous so there isn't any extra overhead for adding this each time.
=> consistent drawing behavior

labelbox/data/ontology.py
* Throw an error if the schema id does not exist in the ontology
* This was causing weird / unclear errors later on when users go to use the ids
=> better error message when schema ids are none

labelbox/client.py, labelbox/exceptions.py
[JIRA TICKET](https://labelbox.atlassian.net/browse/DIAG-884<JIRA_INFO>)
https://github.com/Labelbox/intelligence/pull/6224
is a related PR in intelligence to improve the errors that are thrown
**Changes**
* Handle a couple types of errors that are often thrown in intelligence rather than just handling them with a generic error
* Remove intelligence stack trace from unhandled errors (ideally, though, now none of the MEA errors are unhandled, so this shouldn't be an issue anyways)
=> Improve error handling [DIAG-884]

tests/integration/annotation_import/test_label_import.py, tests/integration/test_label.py, tests/integration/test_labeler_performance.py
update to tests that were previously marked skipped before pending LabelImport. Is supposed to be the following step after annotation_submit_fn was removed from the files
=> updates to tests after implementation of LabelImport

labelbox/data/serialization/ndjson/label.py, labelbox/data/serialization/ndjson/objects.py, tests/data/serialization/ndjson/test_image.py
Not the most elegant solution because we would have to create a concept of a binary mask. But still better than requiring signed urls if the data is not already a url.
I added tests here and also tested against staging on a live import.
=> in-line mask ndjson converter

CHANGELOG.md, labelbox/__init__.py, labelbox/data/annotation_types/types.py
In the latest numpy release support for typing np.ndarrays was added. This broke the interface for our TypedArray object. The changes in this PR restore's the interface
=> numpy typing fix

CHANGELOG.md, labelbox/schema/project.py
Related to ticket https://labelbox.atlassian.net/browse/SE-1295.
Allow SDK to set quota of 0% and 100%. Currently, these values are not accepted.
=> SE-1295: Update upsert_review_queue so quota_factor can accept 1.0 and 0.0

examples/integrations/gcp/utils/requirements.txt, examples/integrations/gcp/utils/resource_manager.py
Ref: https://labelbox.atlassian.net/browse/AL-1338
Original intent was to mitigate the risk of high gcloud bills because of leftover endpoints or long running jobs.
This script can list and delete those plus datasets and models. Can be a quick way to check the status of things from the command line.
I also added a print to direct the user to their GCP console, just so people without gcloud experience don't assume this is the only way to do things.
=> Script to list and delete Vertex AI objects

.github/workflows/python-package.yml, labelbox/schema/organization.py, labelbox/schema/project.py, tests/integration/test_data_rows.py
Initial phase is done, but there looks to be an issue with the filters themselves. Speaking with Utkarsh more on this before requesting a review
=> initial addition to include filters for export_labels

examples/format_notebooks.py, labelbox/data/serialization/labelbox_v1/label.py, tox.ini
Annotation types are not designed to work with gcs or s3 uris. We recently updated the exporter to not sign uris which is a breaking change. This will unblock but users will still have to define a custom function for downloading the asset.
=> uri support

labelbox/__init__.py, labelbox/schema/project.py
LabelGenerator was accidentally imported to type
=> FIX: remove label generator

examples/integrations/gcp/utils/resource_manager.py
Script was crashing with custom jobs. Removev Redundant "has_failed" column to fix.
(Running, success or failed status is already displayed in the state column)
=> fix resource_manager script crash on custom jobs

labelbox/__init__.py, labelbox/client.py, labelbox/schema/organization.py, labelbox/schema/project.py, labelbox/schema/project_resource_tag.py, labelbox/schema/resource_tag.py, tests/integration/test_project.py
This PR adds two calls to our SDK,
- get_resource_tags which returns a list of resource tags for the organization
- create_project_resource_tags(tag_ids = []): to create/associate resource tags to projects
TDD: https://docs.google.com/document/d/1r60QC3Ch_zu3UPEEMVF9R0la4OQlelmQngfhIPMIPEo/edit#heading=h.ql1qz79ruc9v
Jira
https://labelbox.atlassian.net/jira/software/c/projects/ORCH/boards/52?modal=detail&selectedIssue=ORCH-835
https://user-images.githubusercontent.com/74563614/153306005-1aab13fc-42db-459e-b5f0-e8e136e6a0b7.mov
=> get_resource_tags and create_project_resource_tags

examples/integrations/gcp/src/jobs/etl/images/bounding_box/bounding_box_etl.py, examples/integrations/gcp/src/jobs/etl/images/classification/classification_etl.py, examples/integrations/gcp/src/jobs/etl/text/classification/classification_etl.py, examples/integrations/gcp/src/jobs/etl/text/ner/ner_etl.py
Write data row ids out to the training file. 
According to the vertex docs:
`dataItemResourceLabels` - Can contain any number of key-value string pairs. 
https://cloud.google.com/vertex-ai/docs/datasets/prepare-image#single-label-classification
=> add datarow to etl

labelbox/schema/model_run.py, tests/integration/annotation_import/test_model_run.py
Looking to generate annotations similar to project.export_labels()
Currently we cannot do project.label_generator() which would return Label objects as it may struggle to infer media type.
=> [AL-1623] - ModelRun Export Annotations

labelbox/data/annotation_types/classification/classification.py, labelbox/schema/ontology.py
Warnings for when an ontology includes Dropdown, or when a user tries to create a Dropdown annotation type.
This includes:
* creation of a Dropdown class object
* pulling an OntologyBuilder object from an existing project or ontology
* creation of a Dropdown annotation type
=> [AL-1688] Inclusion of warning messages

CHANGELOG.md, labelbox/data/annotation_types/classification/classification.py, labelbox/schema/ontology.py
When the changelog is officially set up for the next release, the X's must be filled in for the date.
=> [AL-1688] Dropdown Deprecation Changelog Update

examples/basics/user_management.ipynb
updated field : "DUMMY_EMAIL = \"SET THIS\"\n", instead of "DUMMY_EMAIL = \"<SET THIS>\"\n" that lead some customer using email like <someone@domain.com>
=> updated user_management.ipynl

tests/integration/test_project.py
Mark tag test until one of 2 following conditions are met:
* We have an easy way to delete all tags through the sdk for an organization
* We have unlimited tag permissions for all testing organizations
Reason:
* Tests will consistently fail due to the fact that orgs are limited to a default of 3 tags. 
* We do not want to manually delete tags every time we want to push to sdk
=> Skip Tag Test

tests/integration/conftest.py
Adding a 2s sleep after project.setup() prior to fetching the project's ontology in order to reduce the inconsistency of the API.
Grabbing an ontology immediately after the project was set up would occasionally cause a keyerror.
=> Integration Tests - Update Configured Project with Sleep

examples/annotation_types/basics.ipynb, examples/annotation_types/converters.ipynb, labelbox/schema/project.py
This will need to follow standard deprecation procedure once approved.
Calling project.label_generator() will now determine the type of labels and provide either video, or image/text. Mixed data types will still need to use project.export_labels()
=> [AL-1283] Merge Label Generator and Video Label Generator

labelbox/client.py
Now usage information for methods will actually show for usages like below.
```
project = client.get_project(PROJECT_ID)
export_url = project.export_labels() 
```
=> Add type annotation to get_project

examples/label_export/text.ipynb, examples/label_export/video.ipynb
Significantly revised the text and video export notebooks to demonstrate how to parse through the exports in both cases, which was especially needed for video example, and how to convert annotation types to ndjson for text. I also removed the very project-specific example at the end of the original text notebook, which had no reusability. Additionally, the video export notebook also came with a project ID, but the visualization task at the end is well-written and applies to all projects, so I kept it.
=> revised video and text export notebooks

.github/workflows/python-package.yml, Dockerfile, Makefile, pytest.ini, tox.ini
update to use plugin rerunfailure for pytest. reruns 3 times after failure for any failed tests
=> [AL-1885] Update to Pytest Runs

labelbox/schema/organization.py, tests/integration/test_project.py
update to test_project. still leaving as skip as there is an issue wIth tag fetching. also updated resource creation code for better error messaging
=> [AL-1777] Update to Resource Tag test code

tests/integration/test_batch.py, tests/integration/test_data_row_metadata.py
We did not have logging for it before, but this was updated - deleting a dataset twice technically tries to delete a nonexistent dataset. Because of this, the SDK tests now fail from test_batch.py. This update removes the double delete problem
=> [AL-2196] Test Update for Test batch

labelbox/__init__.py
We will be no longer supporting 3.6 starting 6/1/22. We will support 3.7-3.9
=> [AL-2193] Deprecation message for Python 3.6

tests/integration/conftest.py
update to onprem test case input from instance id to hostname
After talking to Joanna/Joe, sounds like the hostname will be highly variable. At the same time, they mentioned that they did not usually have any problems with `hostname` appended with /api/_gql.
=> [AL-2173] Update to on-prem test case input

CHANGELOG.md, labelbox/__init__.py, labelbox/orm/model.py, labelbox/pagination.py, labelbox/schema/batch.py, labelbox/schema/project.py, tests/integration/test_batch.py, tests/integration/test_project.py
Adds
```project.batches()```
```batch.export_data_rows()``` (depends on intelligence pr #8171)
```Batch.project()``` fix 
```batch.remove_queued_data_rows()```
=> [AL-2075] Batch list and export

Dockerfile
Running tests locally on Mac M1's was failing with ```OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].```
Adding `libgeos-dev` to the install list in Dockerfile resolves the issue.
=> [X-0] Fix M1 test issue

labelbox/client.py, labelbox/exceptions.py, labelbox/orm/model.py, labelbox/orm/query.py, labelbox/schema/batch.py, labelbox/schema/data_row.py, labelbox/schema/data_row_metadata.py, labelbox/schema/dataset.py, tests/integration/test_client_errors.py, tests/integration/test_data_row_metadata.py, tests/integration/test_data_rows.py
https://labelbox.atlassian.net/browse/AL-2218
Changes:
- Adding metadata_fields as an optional parameter to create_data_row()
- Setting metadata_fields as a new Field in DataRow as a new field type, List
- Adjusting graphql query parameters to adjust for metadataFields
- Caching metadata ontology
Heads up:
- Thinking of a major version upgrade from 3.20.x to 3.21.0 for the overall change. I will make this version upgrade once all parts of the TDD are implemented
Tests:
- Added a case for setting metadata_fields for data row integration test
=> [AL-2218] Adding optional metadata_fields to create_data_row()

labelbox/client.py, tests/integration/test_client_errors.py, tests/integration/test_data_rows.py
Remove `ResourceCreation` error, since we're just throwing `MalformedRequestError` for invalid metadata from API side
=> [AL-0] Modify test for data row with metadata creation

CHANGELOG.md, labelbox/__init__.py, labelbox/schema/project.py
[JIRA ticket](https://labelbox.atlassian.net/browse/AL-2384)
Increases `Project.create_batch()` timeout, since for batch sizes > 10,000 thirty seconds usually isn't enough
=> [AL-2384] Increase create_batch timeout

CHANGELOG.md, labelbox/__init__.py
Need to release this change when the backend changes for renaming customMetadata to metadataFields goes in
=> [AL-0] __init__ and changelog changes for 3.22.1

labelbox/schema/data_row_metadata.py, tests/integration/conftest.py, tests/integration/test_data_row_metadata.py
https://labelbox.atlassian.net/browse/AL-2592
https://labelbox.atlassian.net/browse/AL-2593
https://labelbox.atlassian.net/browse/AL-2594
=> [AL-2592] [AL-2593] [AL-2594] Create/Update/Delete custom metadata schema

labelbox/schema/dataset.py, tests/integration/conftest.py, tests/integration/media/bulk_conversation.json, tests/integration/test_client_errors.py, tests/integration/test_dataset.py
Add multiple conversations from one JSON file using the create_data_rows function in the Dataset. The format expected is matching what is in the docs [here](https://docs.labelbox.com/reference/text-conversational). Also changed the staging URL used for pytest.
The test ran checks for `Dataset.data_rows()` to match the length of the list passed in from the upload.
Check for keys fields to be included in each message passed in the `conversationalData`.
=> Ability to bulk upload conversations using Dataset.create_data_rows() + update staging URL

labelbox/data/serialization/ndjson/label.py, labelbox/data/serialization/ndjson/objects.py, tests/data/assets/ndjson/video_import.json, tests/data/serialization/ndjson/test_video.py
- Added video point and video polyline support for serialization/deserialization, along with test cases
- fixed deserialization to pass in uuid for video annotations
- fixed infer_media_type()
=> [AL-2954] Add video point and polyline support in annotation serialization

labelbox/schema/dataset.py, tests/integration/test_dataset.py
update to include max datarow operations
=> [AL-3045] Max Datarow Upload Per Operation

labelbox/data/annotation_types/data/raster.py, labelbox/data/annotation_types/data/text.py, labelbox/data/serialization/coco/categories.py, labelbox/data/serialization/coco/instance_dataset.py
the coco converter fails if the annotations are empty. Now we simply skip those anntotations. I also updated the retry logic for failed mask downloads so that it will be more robust.
=> handle empty annotations

labelbox/client.py
**Before**
```log
raise labelbox.exceptions.LabelboxError(
labelbox.exceptions.LabelboxError: Failed to upload, message: None('Failed to upload, message: None', None)
```
**After**
```log
raise labelbox.exceptions.LabelboxError(
labelbox.exceptions.LabelboxError: Failed to upload, message: File upload error - invalid file extension for for file geomap.tif('Failed to upload, message: File upload error - invalid file extension for for file geomap.tif', None)
```
=> [AC-242] Add error message detail to the LabelboxError when data row uploads fail.

labelbox/schema/project.py
The current logic subtracts `sleep_time` every iteration regardless of whether the request actually took that long.  This change ensures that `timeout_seconds` seconds pass before returning `None`
=> Fix timeout logic

labelbox/schema/project.py
This prevents the export from returning None as the url, unless a timeout occurs.
=> Check if export download url is None before returning

tests/integration/conftest.py
8/3/2022 - Using IMG_URL=picsum... is giving an error `invalid magic bytes for file`
This is circumvented by using alternative websites. This PR is to use an alternative lorem image generator.
=> [AL-0] Picsum Alternative

tests/integration/conftest.py, tests/integration/test_data_row_metadata.py, tests/integration/test_label.py, tests/integration/test_project.py
In `image_url` pytest fixture, we were uploading an image with json content type and filename via `client.upload_data`, which is pretty illegal, and now being caught by the updates in the client file upload validation in the backend that @jakub-borowski introduced. This was causing the original picsum url to not work. We then attempted to use `placeholder` as an alternative to picsum, but that website seems to be a bit more unreliable. Reverting back to picsum, and setting the content type and filename properly in `image_url` fixture fixes the issue
=> [AL-0] Fix image_url fixture to use jpeg when uploading data

labelbox/data/serialization/coco/instance_dataset.py
Iterating over multipart in shapely can now be done using `object.geoms` which returns a list.
Code is updated so that we now iterate over the list result of the `object`
Current documentation from shapely:
`...Members of a multi-point collection are accessed via the geoms property or via the iterator protocol using in or list()...`
[link to shapely manual](https://shapely.readthedocs.io/en/stable/manual.html)
```
pprint.pprint(list(points.geoms))
[<shapely.geometry.point.Point object at 0x...>,
<shapely.geometry.point.Point object at 0x...>]
```
Since we are expecting everything to be multicollection objects outside of just a polygon, we run `.geoms` against anything that is not polygon here.
=> [AL-3169] Update to shapely geoms

labelbox/schema/asset_attachment.py
This change is allowing us to use Python SDK to set new attachment types for text - RAW_TEXT and TEXT_FILE.
More documentation about this change is available [here](https://github.com/Labelbox/intelligence/pull/9837)
=> [CCV-1501] Add two new attachment types - raw_text and text_file

labelbox/schema/data_row.py
=> [AL-3099] Add global_key to data_row

CHANGELOG.md, labelbox/client.py, labelbox/schema/project.py, tests/integration/annotation_import/conftest.py, tests/integration/conftest.py, tests/integration/test_batch.py, tests/integration/test_project.py
Updating a project's queue mode will soon be disallowed through the API service, so this PR migrates the test code to instead set the queue mode upon project creation.
=> [QQC-558] Remove test code updating queue_mode for a Project

CHANGELOG.md, labelbox/schema/project.py, tests/integration/test_export.py
https://labelbox.atlassian.net/browse/AC-554
The API already support having a timestamp. This PR just revise the validation rule to allow parsing timestamp.
I tested with an ad-hoc script as follow:
```
import labelbox
LB_API_KEY = "REDACTED"
ENDPOINT = "https://api.labelbox.com/graphql"
client = labelbox.Client(LB_API_KEY, ENDPOINT)
project = client.get_project(project_id="cl7ezmshm0ddu0757g5wu3znc")
labels = project.export_labels(download=True, start="2022-09-02", end="2022-09-02 22:44:34")
for lbl in labels:
print({
"ID": lbl["ID"],
"Created At": lbl["Created At"]
})
print("done")
```
First run: no start / end filters:
```
$ poetry run python ./[export_test.py](http://export_test.py/)
{'ID': 'cl7kqyhy70m0q070e5m4j6rni', 'Created At': '2022-09-02T19:02:43.000Z'}
{'ID': …
```
=> [AC-554] project.export_labels: supporting filtering by time in start/end args

labelbox/schema/task.py
- In order to support a backend change that is going to allow data row imports to succeed even when a small chunk of data rows might not get created, we're introducing the notion of `failed_data_rows`. These data row inputs will be returned in the results file on an import task.
- Remove unused imports.
Example output of a result file:
```jsonc
{
"createdDataRows": [
{
"id": "cl8kui84n019hatrw5c17gdcl",
"rowData": "https://storage.googleapis.com/image.jpeg",
"datasetId": "cl8kui65h00bxatrwc2jifig0"
},
// additional created rows...
],
"errors": [
{
"message": "Failed to create data rows after 5 retries. This chunk's data rows will not be imported.",
"failedDataRows": [
{
"rowData": "https://storage.googleapis.com/image.jpeg"
},
// additional failed rows...
]
},
{
"message": "Failed to …
```
=> [AC-549] Introduce failed_data_rows to the Task class.

labelbox/client.py
Since we'll be adjusting default createProject behavior to prefer batch projects, we want to give an early heads-up to our customers.
=> [X-0] Warn if queue_mode is not defined

labelbox/client.py, labelbox/schema/task.py, tests/integration/test_data_row_media_attributes.py, tests/integration/test_data_row_metadata.py, tests/integration/test_data_rows.py, tests/integration/test_global_keys.py, tests/integration/test_task.py
- Changed failed_data_rows to a property
- Fixed issue with task always reporting warning, due to a bug with failed_data_rows check condition
- Fixed `test_create_data_rows_with_invalid_metadata` on assertions
- Fixed `test_get_data_row_ids_for_invalid_global_keys` to not falsely report PARTIAL SUCCESS
- Fixed `test_task_errors` on assertions
=> [AL-3872] Fix SDK build tests

tests/integration/test_export.py, tests/integration/test_label.py
Adding sleep(10) between label creation, and label exporter, as there can be replication lag
=> [AL-0] Add sleep before label exporter

tests/integration/test_data_rows.py, tests/integration/test_task.py
#Description 
Fixing data row tests as part of the new import mechanism
=> Fixing data row import tests

labelbox/data/annotation_types/geometry/mask.py, labelbox/data/serialization/coco/instance_dataset.py, labelbox/data/serialization/coco/panoptic_dataset.py
There is a small chance that our algorithm for creating polygons from rasters creates small self intersections. Ultimately these polygons become invalid and errors are thrown when we attempt to use the invalid polygons.
=> fix coco invalid polygons

tests/integration/annotation_import/conftest.py, tests/integration/conftest.py, tests/integration/test_filtering.py, tests/integration/test_relationships.py, tests/integration/test_sorting.py
Due to recent changes to default createProject behavior, we've started to default to `batches` if no queue mode is provided. Thus, we need to adjust integration tests.
Since the default behavior change is already on staging, I've run e2e tests against it. They all pass.
Tandem PR in API that adjusts the behavior: https://github.com/Labelbox/intelligence/pull/11294
=> [X-0] Adjust integration tests to explicitly define queue mode

CHANGELOG.md, labelbox/schema/batch.py, labelbox/schema/consensus_settings.py, labelbox/schema/data_row_metadata.py, labelbox/schema/project.py, labelbox/utils.py, tests/integration/conftest.py, tests/integration/test_batch.py
Tandem PR in API that needs to be merged before this: https://github.com/Labelbox/intelligence/pull/11383 (done)
This is part of project paradigm which is set to release on 2nd November. As part of the changes, we'll prefer customers to provide consensus settings per batch, rather than per project.
Updates to our SDK documentation are coming after this PR gets in.
=> [QQC-755] Allow to pass batch consensus settings when creating a batch

labelbox/data/serialization/labelbox_v1/label.py
When we attempt to guess the media type from the file name we previously only checked lower case characters. This PR changes the behavior to first convert all file names to lower case before checking the extension.
=> fix media type checks

CHANGELOG.md, labelbox/client.py, labelbox/schema/project.py
Part of project paradigm set to release 2nd November. Ran e2e tests after doing the modifications to verify they still pass.
=> [QQC-772] Add deprecation warnings for creating Dataset projects & using LPOs

labelbox/schema/data_row.py, tests/integration/test_data_rows.py
We recently updated the backend to accept row data as stringified json to support data rows that are composed of multiple pieces of information. In #734 we changed the SDK to support this for data row creation as well.
This pr is to change that behavior for data row update.
=> update create data row row_data to accept dict

labelbox/schema/data_row.py
This needs to go in first: https://github.com/Labelbox/intelligence/pull/11988
=> [QQC-1061] Add get_winning_label_id to data row

labelbox/pagination.py, tests/integration/test_dataset.py
Adding more convenience to users when they want to get a predefined number of results from the paginated collection.
old way:
```
data_rows = dataset.data_rows()
data_row = next(data_rows)
```
new way:
```
data_row = dataset.data_rows().get_one()
```
old way:
```
data_rows = dataset.data_rows()
first_ten = []
for data_row in data_rows:
first_ten.append(data_row)
if len(first_ten) >= 10:
break
```
new way: 
```
data_rows = dataset.data_rows().get_many(10)
```
important note. These methods are idempotent. That means: 
1. They can be called as many times as wanted and the result will be the same. E.x. get_one will **always** return first one result. It is not equivalent to calling next().
2. get_many will **not** call API in case it already has needed amount of data. This way to safe …
=> add get_one and get_many methods to paginated collection

labelbox/orm/db_object.py, labelbox/orm/model.py
Tested on nested dicts and dicts with nested objects.
Before: 
After:
Before: 
After:
=> pretty print objects values

labelbox/client.py, labelbox/schema/media_type.py
[CVV-1905](https://labelbox.atlassian.net/browse/CCV-1905)
[CVV-1906](https://labelbox.atlassian.net/browse/CCV-1906)
[CVV-1907](https://labelbox.atlassian.net/browse/CCV-1907)
-----
Description
-----
Added optional argument "media_type" to two functions:
- create_ontology_from_feature_schemas
- create_ontology
Risk Level: Medium
-------
How to test
-----
```python
from labelbox import OntologyBuilder, Tool, Classification, Option, Client, MediaType
client = Client(api_key="", endpoint="http://localhost:8080/graphql")
ontology_name = "sdk-ontology-2"
feature_schema_cat_normalized = {
'tool': 'polygon',
'name': 'cat',
'color': 'black'
}
ontology_normalized_json = {
"tools": [feature_schema_cat_normalized],
"classifications": []
}
ontology = client.create_ontology(
name=ontology_name, …
```
=> [CCV-1905][CCV-1906][CCV-1907] Pass media type when creating an ontology

scripts/update_sdk_version.sh
Adding a helper script to facilitate updating SDK version.
```
./scripts/update_sdk_version.sh -v 3.34.0
```
=> [AL-4434] Add helper script to update SDK version

examples/integrations/detectron2/coco_object.ipynb
1. Change how the labelbox module is imported
2. 
From:
```!pip install -q "git+https://github.com/Labelbox/labelbox-python@ms/coco#egg=labelbox[data]"```
To:
```!pip install -q "labelbox[data]"```
3. Update the URL for `coco_utils.py`
4. 
From:
```https://raw.githubusercontent.com/Labelbox/labelbox-python/ms/coco/examples/integrations/detectron2/coco_utils.py```
To:
```https://raw.githubusercontent.com/Labelbox/labelbox-python/develop/examples/integrations/detectron2/coco_utils.py"```
=> Update labelbox import and coco_utils.py URL

tests/integration/conftest.py, tests/integration/test_data_row_media_attributes.py
Fixed two places where we were using a Generator to verify existence of the label, which was resulting in an error message that was hard to decipher
=> [AL-0] Better error handling for label creation during test

tests/integration/conftest.py, tests/integration/test_data_row_media_attributes.py, tests/integration/test_data_row_metadata.py, tests/integration/test_export.py, tests/integration/test_project_setup.py
- Added a step to wait for label to finish processing in `configured_project_with_label`
- Added a step to wait for data row to finish processing for tests that rely on media_attributes to be populated, specifically tests that use label exports (labels on data rows that have not been processed are not exported).
=> [AL-0] Fix tests that were flaky due to label creation

examples/annotation_import/video.ipynb
Created examples with all the annotation types supported for videos Created all examples with new NDJSON format annotations
=> New annotation import format-video

examples/annotation_import/image.ipynb
Old link was pointing to an image_annotation_import.ipynb instead of image.ipynb
=> Update colab links

labelbox/client.py, tests/integration/test_global_keys.py
As part of https://github.com/Labelbox/intelligence/pull/12986/files PR, for assign function, if incoming DataRow doesn't exist, or is not part of user's org, or is deleted, it gets returned in invalidDataRowsGlobalKeys bucket, so enhancing the error message for that
=> Fix wording for assign_global_keys_to_data_rows error message

tests/integration/test_data_row_metadata.py, tests/integration/test_data_rows.py, tests/integration/test_task.py
SDK tests are failing bc error message thrown from backend is different
```
FAILED tests/integration/test_data_rows.py::test_data_row_bulk_creation_with_same_global_keys - AssertionError: assert 'Data rows
contain duplicate global keys' == 'Data rows contain empty string or duplicate global keys, which are not allowed'   
```
Also fixed tests that are failing due to embeddings sunsetting
=> [AL-0] Fix test_data_rows.py that expects an error message from backend

CHANGELOG.md, docs/source/conf.py, labelbox/__init__.py
Verified that there are no missing user-facing updates in the change log.
=> Preparing for 3.37.0 release

labelbox/schema/data_row.py, tests/integration/test_data_rows.py
Add the support of an optional `attachment_name` parameter to `data_row.create_attachment()` to match JSON creation.
```
data_row.create_attachment(attachment_type="IMAGE_OVERLAY", attachment_value="https://storage.googleapis.com/labelbox-sample-datasets/Docs/cir.jpg")
data_row.create_attachment(attachment_type="IMAGE_OVERLAY", attachment_value="https://storage.googleapis.com/labelbox-sample-datasets/Docs/weeds.jpg", attachment_name="Weeds")
```
Specific tests were added to verify the creation of an attachment with or without a name.
=> Add attachment_name support to create_attachment()

CHANGELOG.md, labelbox/__init__.py, labelbox/data/annotation_types/__init__.py, labelbox/data/annotation_types/collection.py, labelbox/data/annotation_types/geometry/geometry.py, labelbox/data/annotation_types/geometry/line.py, labelbox/data/annotation_types/geometry/mask.py, labelbox/data/annotation_types/geometry/polygon.py, labelbox/data/annotation_types/geometry/rectangle.py, labelbox/data/metrics/iou/calculation.py, labelbox/schema/annotation_import.py, labelbox/schema/bulk_import_request.py, labelbox/schema/model_run.py, labelbox/schema/serialization.py, labelbox/types.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_bulk_import_request.py, tests/integration/annotation_import/test_label_import.py, tests/integration/annotation_import/test_mea_prediction_import.py
SDK objects can now be imported with:
```
import labelbox as lb
import labelbox.types as lb_types
```
* Update `__init__.py` file include imports used by notebooks but not in the root namespace.
* Create a types module that imports annotation types
* Update AnnotationImport and BulkImportRequest to serialize Python annotations.
Tested the dependency on labelbox[data] by uninstalling shapely and running a notebook that uses NDJson-based annotation import.
Notebooks will be updated in a subsequent PR, there have been a number of updates in `develop` since this PR was opened and a large number of conflicts. I'll redo the renaming instead of resolving conflicts.
=> [AL-4858][AL-4860] Reduce imports and hide NDJsonConverter

labelbox_dev/data_row.py, labelbox_dev/session.py, labelbox_dev/task.py
- Renamed occurrences of `data_row_ids` to `ids
- Introduced `DataRow.update_many()` and `DataRow.delete_many()`
- Async task classes for update and delete async jobs
- Disclaimer: Task.errors doesn't return anything b/c we're not properly storing errors using bulk ops
=> [AL-4046] [AL-4048] Bulk DataRow update and delete

labelbox/schema/export_params.py, labelbox/schema/model_run.py, labelbox/schema/project.py, tests/integration/annotation_import/test_model_run.py, tests/integration/test_project.py
* Removed a param in gql and needed to update here.
* Tests were added in because we are starting internal testing and exports should be stable.
=> fix exports v2, enable tests

examples/test_notebooks.py, requirements.txt, tox.ini
This is a new test added that was only meant to be run locally, but it is breaking the SDK tests. Adding dependencies for this test and skipping it.
=> Skip notebook tests and add test dependencies to docker image

labelbox/schema/data_row_metadata.py
Improve error messaging around metadata validation to include which metadata is failing, and which data_row_id it's failing on
=> [AL-0] Improve error msg for metadata validation

examples/annotation_import/image.ipynb, examples/prediction_upload/image_predictions.ipynb, examples/prediction_upload/text_predictions.ipynb
* lb_serialzers imports were unused, removing them
* examples/label_export/images.ipynb was invalid, it was missing some required metadata and not in the format the pre-commit hook expects. Fixing that.
=> [AL-4860] Remove lb_serializers imports and fix invalid notebook

CHANGELOG.md, docs/source/index.rst, labelbox/__init__.py, labelbox/orm/model.py, labelbox/schema/project.py, labelbox/schema/task.py, labelbox/schema/task_queue.py, tests/integration/conftest.py, tests/integration/test_task_queue.py
* Added new entity TaskQueue
* Added new methods in Project:
* Obtain a list of TaskQueues owned by the Project
* Move a list of data rows to a specified TaskQueue
=> [QQC-1484] Support move to task action

tests/integration/annotation_import/test_model_run.py, tests/integration/test_project.py
Errors has been removed from the payload and put in a separate field. 
I have another pr for adding this back to the tests using the appropriate field.
=> fix export tests

labelbox/__init__.py, labelbox/client.py, labelbox/orm/model.py, labelbox/schema/slice.py
Adds the new ModelSlice entity and get method
=> [AL-4886] Introduce ModelSlice

labelbox/schema/model_run.py, labelbox/schema/project.py
We do have backend default taskName implemented at this moment, there's no need for the SDK to have it too.
=> [X-0] Fix SDK default task name

labelbox/data/serialization/coco/panoptic_dataset.py
Currently, this method fails since coco_segment_info is not defined in the scope of the "elif" clause for  (Polygon, Rectangle) annotations
=> Potential fix for the COCO panoptic method

labelbox/schema/model_run.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_mea_prediction_import.py
Stories: https://labelbox.atlassian.net/browse/AL-2960
This updates the ModelRun#upsert_labels as per this [TDD section](https://docs.google.com/document/d/1pKZBKa5Z9O7AlSPvaW7jsvWBp4sHLRVpZiLM_xaT6WQ/edit#bookmark=id.cnyn7tj2ykj0)
NOTE: includes some corrections YAPF made me do
=> Add logic to upload labels by project id to model run

labelbox/schema/export_filters.py, labelbox/schema/project.py, tests/integration/test_project.py
https://labelbox.atlassian.net/browse/AL-5192
Added support for `last_activity_at / label_created_at` filters which are transformed into search query params before making GQL call
=> [AL-5192] Add last_activity_at / label_created_at export v2 support

labelbox/schema/export_params.py, labelbox/schema/model_run.py, labelbox/schema/project.py, tests/integration/test_project.py
Adds support for media type overrides filed
=> [AL-4990] Add media type override

CHANGELOG.md, labelbox/schema/model_run.py, tests/integration/annotation_import/test_model_run.py
Depends on: https://github.com/Labelbox/intelligence/pull/13712
=> [AL-4870] Split model run data rows using global keys

labelbox/data/annotation_types/__init__.py, labelbox/data/annotation_types/annotation.py, labelbox/data/annotation_types/label.py, labelbox/data/annotation_types/ner/__init__.py, labelbox/data/annotation_types/ner/conversation_entity.py, labelbox/data/annotation_types/ner/document_entity.py, labelbox/data/serialization/ndjson/label.py, labelbox/data/serialization/ndjson/objects.py, tests/assets/conversation-1.json, tests/data/annotation_types/test_ner.py, tests/data/assets/ndjson/conversation_entity_import.json, tests/data/assets/ndjson/conversation_entity_without_confidence_import.json, tests/data/serialization/ndjson/test_text_entity.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_bulk_import_request.py, tests/integration/annotation_import/test_conversation_import.py, tests/integration/conftest.py
story: https://labelbox.atlassian.net/browse/AL-5107
=> [AL-5107] Vb/conversational annotation al 5107 2

labelbox/data/annotation_types/__init__.py, labelbox/data/annotation_types/annotation.py, labelbox/data/annotation_types/label.py, labelbox/data/serialization/ndjson/label.py, labelbox/data/serialization/ndjson/objects.py, tests/data/serialization/coco/test_coco.py, tests/data/serialization/ndjson/test_dicom.py
* Add `DICOMObjectAnnotation` and `GroupKey` enum to support annotation import using Python objects.
* Update `NDJsonConverter` to serialize/deserialize `DICOMObjectAnnotation` to/from the NDJson format.
Note: coco tests did not cleanup files written to directory which resulted in only the first execution of these tests working the and subsequent ones failing. These have been updated to cleanup temporary files.
=> [AL-5108] Add DICOM polyline annotation kind

labelbox/client.py, labelbox/schema/data_row.py, labelbox/schema/dataset.py, labelbox/schema/export_filters.py, labelbox/schema/export_params.py, labelbox/schema/project.py, labelbox/schema/slice.py, tests/integration/test_data_rows.py, tests/integration/test_dataset.py, tests/integration/test_slice.py
[AL-5278](https://labelbox.atlassian.net/browse/AL-5278)
[AL-5279](https://labelbox.atlassian.net/browse/AL-5279)
[AL-5280](https://labelbox.atlassian.net/browse/AL-5280)
**Edit: Added test cases for all the methods, no need to run the below**
Need to prepare staging acc to add tests, right now can be tested by checking out to the branch and:
```
pip install -e .  
```
```
from labelbox import Client
API_KEY = API_KEY
ENDPOINT = STAGE_URL
SLICE_ID = 
client = Client(api_key=API_KEY, endpoint=ENDPOINT)
slice = client.get_catalog_slice(SLICE_ID)
task = slice.export_v2(params={"performance_details": False, "label_details": True})
task.wait_till_done()
task.result
```
[AL-5278]: https://labelbox.atlassian.net/browse/AL-5278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> [AL-5278] [AL-5279] [AL-5260]  Add catalog slice, data row, dataset support

labelbox/data/annotation_types/data/audio.py, labelbox/data/annotation_types/data/conversation.py, labelbox/data/annotation_types/data/dicom.py, labelbox/data/annotation_types/data/document.py, labelbox/data/annotation_types/data/html.py, labelbox/data/annotation_types/data/text.py, labelbox/data/annotation_types/label.py, labelbox/typing_imports.py, labelbox/utils.py, tests/data/annotation_types/test_label.py
When creating a `Label`, the annotation data type class was being changed and the global_key field was disappearing. Example:
```
label = []
label.append(
lb_types.Label(
data=lb_types.ConversationData(
global_key=global_key
),
annotations=[
ner_annotation
]
)
)
```
Output
```
[Label(uid=None, data=VideoData(file_path=None,frames=None,url=None), annotations=[ObjectAnnotation(confidence=None, name='ner', feature_schema_id=None, extra={}, value=ConversationEntity(start=0, end=8, extra={}, message_id='4'), classifications=[])], extra={})]
```
The problem was that Pydantic tries to coerce objects to the first class listed in a Union. See [Pydantic docs](https://docs.pydantic.dev/usage/types/#unions) for more details.
This is fixed by adding a discriminator field (`class_name`) which is …
=> Fix annotation data type coersion by Pydantic

labelbox/schema/data_row_metadata.py
**Description**
Lifting up string metadata limitation to 4096 characters.
=> [AL-5269] Lift up string metadata limitation to 4096 chars

labelbox/data/annotation_types/__init__.py, labelbox/data/annotation_types/annotation.py, labelbox/data/annotation_types/label.py, labelbox/data/annotation_types/video.py, labelbox/data/serialization/labelbox_v1/label.py, labelbox/data/serialization/ndjson/classification.py, labelbox/data/serialization/ndjson/label.py, labelbox/data/serialization/ndjson/objects.py, labelbox/utils.py, tests/data/annotation_types/test_annotation.py, tests/data/annotation_types/test_video.py, tests/data/serialization/ndjson/test_dicom.py, tests/data/serialization/ndjson/test_export_video_objects.py
* Create new module for Video and DICOM annotation kinds
* Add `VideoMaskAnnotation` and `DICOMMaskAnnotation`
* Update `NDJsonConverter` to support new annotation kinds
* Update case conversion util to produce acronyms in uppercase i.e `URI` instead of `Uri`.
Note: This PR includes changes from #999, please review #999 first.
=> [AL-5109][AL-5110] Add Video and Raster Segmentation Annotation Kinds

tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_mea_prediction_import.py, tests/integration/annotation_import/test_model_run.py, tests/integration/annotation_import/test_upsert_prediction_import.py
- Renamed `model_run_with_data_rows`
- Added retry logic to `model_run.exports_v2`
=> [AL-0] Fix model exports v2 flaky tests

labelbox/data/annotation_types/video.py, labelbox/data/serialization/ndjson/objects.py, tests/data/serialization/ndjson/test_dicom.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_data_types.py
* The name field at the root of VideoMaskAnnotation is not needed since this is part of `instances`, therefore it has been removed.
* Added an integration test to ensure VideoMaskAnnotation can be imported.
=> [AL-5110] Fix video raster annotation import

tests/integration/annotation_import/test_label_import.py
The API now validates that an ontology is linked to a project before LabelImport can be done. The two tests were using a project without ontology for label import, updating to use project with ontology.
=> Fix label import test

labelbox/schema/data_row.py, labelbox/schema/dataset.py, labelbox/schema/export_params.py, labelbox/schema/slice.py
- Adds support for project_ids, model_run_ids for the remaining methods (API already supports this)
- Unifies naming (projects_ids -> project_ids, model_runs_ids -> model_run_ids)
=> [X-0] Unify naming, add support to include modelRunIds projectIds

labelbox/data/serialization/ndjson/objects.py
Relationships in conversations were failing because `NDConversationEntity` objects were not using the UUIDs generated by the annotation object.
=> [AL-5407] use UUID from annotation object for ConversationEntity

labelbox/__init__.py, labelbox/schema/data_row_metadata.py, labelbox/utils.py, requirements.txt, setup.py, tests/integration/test_data_row_metadata.py
When creating a data row, datetime metadata in the following iso format was not supported: `2011-05-07T14:34:14+00:00`. Since Python 3.7-3.10 did not have full parsing support for ISO timestamps we were doing datetime manipulation in our parsing code, which resulted in this problem. Python 3.11 has more general support for parsing ISO datetime strings, I have installed a backport to bring Python 3.11 datetime parsing to earlier versions. Tests have been adding for adding / updating datetime metadata.
=> [AL-5276] Fix ISO timestamp parsing

tests/integration/annotation_import/test_model_run.py
Fixed sdk integration tests for export v2 to support https://labelbox.atlassian.net/browse/AL-5450 - change of attribute names for models/model_run to experiments/run
=> Fix specs due to models --> experiments change in export schemas

tests/integration/annotation_import/test_data_types.py, tests/integration/conftest.py
This PR will test changes from https://labelbox.atlassian.net/browse/AL-5592
Note:
- it will require labelbox-schemas version that supports automatic conversion to isoformat (prob 0.0.34 or higher)
- we do not support workflow history export in this test. I have tested it manually. but I did not want to take extra time/risk to convert our project to BATCH mode in order to make workflow history work easily; will do this in the future
=> Add tests for export v2 timestamp exports

labelbox/client.py
If a user is over their LBU limit and tries to do an operation that increases LBUs, the server responds with an error.
That error is returned as an "Internal Server Error", but has the correct 426 status and proper message nested in the error.
This code prevents the SDK from retrying if the user is over their LBU limit, and shows them a OperationNotAllowedException with the message instead. 
This also fixes a bug where the `get_error_status_code` method was looking in the wrong place for the http status code.
Example response from production:
```
{
"message":"LBU limit exceeded, upgrade to continue",
"locations":[
{
"line":1,
"column":45
}
],
"extensions":{
"code":"INTERNAL_SERVER_ERROR",
"exception":{
"response":"LBU limit exceeded, upgrade to continue",
"status":426,
"message":"LBU …
```
=> [PG-61] Don't retry on 426 error code

labelbox/data/serialization/ndjson/parser.py, tests/unit/conftest.py, tests/unit/test_ndjson_parsing.py
Story: https://labelbox.atlassian.net/browse/AL-5458
This is the first step in replacing ndjson library with our own. This PR adds a new module that has exactly the same methods as we use in ndjson library BUT we implement them ourselves using Python json parser. 
The is the same as ndjson uses, so the end result is very similar in terms of parsing and performance. I have added tests, where I generated expected results using the ndjson library
=> [AL-5458] Add our own library to use Python json parser to parse ndjson

labelbox/data/serialization/labelbox_v1/converter.py, labelbox/data/serialization/ndjson/parser.py, labelbox/schema/annotation_import.py, labelbox/schema/batch.py, labelbox/schema/bulk_import_request.py, labelbox/schema/dataset.py, labelbox/schema/model_run.py, labelbox/schema/project.py, labelbox/schema/task.py, mypy.ini, requirements.txt, setup.py, tests/data/serialization/ndjson/test_video.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_bulk_import_request.py, tests/integration/annotation_import/test_mea_prediction_import.py, tests/integration/annotation_import/test_ndjson_validation.py, tests/integration/annotation_import/test_upsert_prediction_import.py, tests/unit/test_ndjson_parsing.py
Story: https://labelbox.atlassian.net/browse/AL-5686
Even though this is a large PR, 90% of files is just a drop-in replacement of the 3d party ndjson library with our own. The rest 10% are important updates to the parser library to address issues from integration tests and removal of the 3d party ndjson library from our setup and requirements.txt
_List of Affected SDK API's_
- prediction upload
- LabelImport#create_from_objects
- MEAPredictionImport#create_from_objects
- export v2
- Batch#export_data_rows
- Dataset#export_data_rows (can just test this and not Batch)
- ModelRun#export_labels
- BulkImportRequest create_from_url, create_from_objects, create_from_local_file, also in errors, statuses etc
- other
- Project#export_queued_data_rows
- Task#failed_data_rows, errors, result etc
=> [AL-5686] Remove ndjson library and replaced it with a custom ndjson parser

examples/prediction_upload/video_predictions.ipynb
Raster segmentation is not supported in model, but is the only segmentation tool supported in the video editor. For the purpose of this notebook, I have removed all masks.
=> Remove raster seg masks from video prediction 

requirements.txt
`typing-extensions` got a new minor version which is not compatible with our SDK
```
File "/usr/local/lib/python3.9/site-packages/labelbox-3.46.0-py3.9.egg/labelbox/data/annotation_types/data/audio.py", line 6, in <module>             
class AudioData(BaseData, _NoCoercionMixin):                                                                                                        
File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__                                                                            
File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer                                                                              
File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__ …
```
=> [AL-0] Pin typing-extensions library to 4.5.0

CHANGELOG.md, docs/source/conf.py, labelbox/__init__.py
* Support for interpolated frames to export v2
* Removed ndjson library and replaced it with a custom ndjson parser
* Remove confidence scores in annotations - video notebook
* Remove raster seg masks from video prediction
* Added export v2 example
* Add SAM and Labelbox connector notebook
=> Prep for sdk release 3.47

labelbox/schema/project.py
Previously batch size was set for all the data rows submitted instead of the ones accepted by the Labelbox backend. This PR is to set the backend response's batch size for the returned entity instead of the length of the inputted list.
=> [QQC-2017]Return batch size of accepted data rows only

labelbox/data/serialization/ndjson/classification.py, tests/data/serialization/ndjson/test_free_text.py, tests/data/serialization/ndjson/test_text.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_mea_prediction_import.py, tests/integration/test_delegated_access.py
Story: https://labelbox.atlassian.net/browse/AL-6008
We are able to support confidence on both free text and nested free text by just moving the `confidence` attribute to `Text` when we convert date to_ from_common. The attribute itself has already been defined via pydantic
Also added unit tests, integration test and test via a notebook
=> [AL-6008] Add confidence to free text Python annotation class

Makefile
Before this change: every time your run a new container is created, and an old one is renamed
Now: a container is removed automatically on exit
=> Add rm option to automatically remove test containers on exit

.github/workflows/python-package.yml, .pre-commit-config.yaml, tests/integration/annotation_import/conftest.py, tests/integration/conftest.py, tests/integration/test_batch.py
- Reduced timeout for `project._wait_until_data_rows_are_processed` to 30s with sleep interval set to 5s
- Reduced number of retries on github action from 5-->3, with reruns-delay from 10s-->3s
- Removed @attila-papai 's` _wait_until_data_rows_are_processed` calls, since it's taken care of in `create_batch`
=> Reduce wait time for DR processing in tests

labelbox/data/annotation_types/types.py, setup.py
Numpy 1.25.0 removes _ GenericAlias in favour of py39 native GenericAlias
=> [X-0] Further numpy fixes

requirements.txt, setup.py
All numpy versions are supported now and Google Colab provides 1.22 by default for Python 3.10 by default, meaning that workspace has to be reloaded initially with current requirements(hence the requirement removal).
=> [X-0] Remkve numpy version lockdown

examples/basics/data_row_metadata.ipynb
1. Added missing methods and examples: https://labelbox.atlassian.net/browse/SN-68
=> updates to metadata notebook

labelbox/orm/model.py, labelbox/orm/query.py, labelbox/pagination.py, labelbox/schema/dataset.py, tests/integration/test_data_rows.py
Story: https://labelbox.atlassian.net/browse/AL-6294
Replaces dataset.data_rows() Relation with a method and implement cursor-based pagination
- Why did I not update the existing data_rows() Relationship but created a new method instead?
- There are specific requirements for how graphql needs to be composed for consumption in Relationship, so I would have to create a Dataset#data_rows_2() node resolver, which I think would be confusing
- The Relationship framework does not support cursor-based pagination and would have to be extended
- BUT we are talking of getting rid of this home-grown framework for sdk 4
- All our queries for cursor-based access use custom methods instead of Relation
And this the work I needed to do:
- make sure my method supports `where` parameter the way Relationship …
=> [AL-6294] Support cursor-based pagination for dataset.data_rows()

labelbox/schema/data_row.py, labelbox/schema/export_filters.py, tests/integration/test_data_rows.py
Also:
- cleaned up for the case of no filters
- added test
=> [AL-6305] Add ability to use data rows ids instead of the whole data row object for DataRow.export_V2()

labelbox/schema/project.py, tests/integration/test_user_management.py
[Ticket](https://labelbox.atlassian.net/browse/EF-369)
A user has requested the roles of project members be returned in the SDK response. This GQL query is already being made by the App. As discussed in the Slack thread, exposing the `accessFrom` field has a risk of introducing latency.
If possible, the updated query should be released for beta testing to further test the performance when used for programmatic access. 
[Slack Thread](https://labelbox.slack.com/archives/C03PTTCEFUJ/p1690372488230829)
[Datadog APM](https://app.datadoghq.com/apm/services/lb-api-public/operations/graphql.execute/resources?env=labelbox-193903-prod-usc1&graphType=flamegraph&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap50 …
=> [SE-2960] Add roles to project members qgl query

tests/integration/test_data_rows.py
In this test case `test_create_tiled_layer` we import geo data and provide a media type hint once. 
It was TMS_SIMPLE before but the tile content actually has TMS_GEO data indicated by `"epsg": "EPSG4326"`
In pre-ADV world both TMS_SIMPLE and TMS_GEO media attribute hints are validated with the same logic but this is not true for ADV world where we have a bit stricter validation logic.
So in pre-ADV both TMS_SIMPLE and TMS_GEO works but in ADV world only TMS_GEO, hence I make this small change here.
=> [AL-6791] fix media type hint

tests/integration/test_client_errors.py, tests/integration/test_data_rows.py, tests/integration/test_dataset.py, tests/integration/test_filtering.py, tests/integration/test_labeling_parameter_overrides.py, tests/integration/test_ontology.py, tests/integration/test_pagination.py, tests/integration/test_project.py
This is part I of sdk test optimization and stabilization story https://labelbox.atlassian.net/browse/AL-6133
As a first step, I have taken a look at the top 10 slowest execution across github and codefresh and 6 out of 10 were tests (as opposed to fixtures) and some had consistently super long execution times of 500-1000+s. The immediate cause was that our test orgs had 30K+ undeleted (read 'leaked') projects and datasets and those tests were executing calls like `client.get_projects()` (also not a very good thing to do in test).
I have since set all those leaked data to `deleted` on stage and that in itself took a successful test run from 20-28 mins on codefresh to 10-15 mins and on githib from 20 mins - 1hour to 20-30 mins (based on my observations)
Improvements in this PR:
- rewriting …
=> [AL-6133] Optimize and stabilize sdk integration tests part I

tests/integration/annotation_import/test_mea_prediction_import.py, tests/integration/annotation_import/test_model_run.py
Due to a recent change in how we're adding data rows to a model run now we must make sure the all the data rows that were recently imported have finished processing at first.
=> wait until DRs are processed before adding them to a model run

CHANGELOG.md, docs/source/conf.py, labelbox/__init__.py
=> Pre-release PR for 3.51.0

tests/integration/test_data_rows.py
ADV does not validate the passed media type hint when performing async import jobs, so we shouldn't test that either.
=> [AL-6743] skip invalid media type validation when ADV is enabled

tests/integration/test_task.py
We can't use a snapshot because the error ADV returns contain a unique error code for easier backtracking.
=> [AL-6729] assert adv task errors separately

tests/integration/test_global_keys.py
Until we agree on the strategy regarding global key sanitization and validation in ADV, I fix this single failing test case to unblock further UAT. Follow up ticket: https://labelbox.atlassian.net/browse/AL-6929
=> [AL-6740] assert adv global key errors separately

tests/integration/export_v2/test_legacy_export.py, tests/integration/test_batch.py, tests/integration/test_project.py
Due to improvement in this [PR](https://github.com/Labelbox/intelligence/pull/16571) we no longer need the extra 5 seconds of delay between creating and exporting a batch.
=> Remove sleep between creating and exporting a batch

tests/integration/test_data_rows.py
ADV now throws when some data rows were not imported during a bulk sync import request. Fixing test case to reflect this change. Needs this [PR](https://github.com/Labelbox/intelligence/pull/16544) first
=> Improve ADV assertion for bulk sync import

tests/integration/test_data_rows.py, tests/integration/test_global_keys.py
After we [aligned](https://github.com/Labelbox/intelligence/pull/16595) global key validation and sanitization in ADV to match with pre-ADV we got 2 tests to change a little bit for ADV.
=> [AL-6929] adjust ADV specific asserts

tests/integration/test_filtering.py
by removing dataset query testing part, since it is not applicable to BATCH projects any more
This fix is actually part of another PR, much bigger one: https://github.com/Labelbox/labelbox-python/pull/1211/files#diff-c71e832deed83f6b10c3d381df572470ed31ce5d7942123235f7b8c868aa3b20
I am just pulling it here in a separate fix
Background:
- @attila-papai  (and also you can see yourself in the logs) pointed that failure occurs here https://github.com/Labelbox/labelbox-python/blob/5275d8e7e990cd7a7bc6c75cdf5b971aa1fb43b1/tests/integration/test_filtering.py#L62-L65
- upon further review, I have discovered that this part of the test originally was testing dataset.project (see https://github.com/Labelbox/labelbox-python/blob/ee996acf05ab5ef30b21f61d3fe5c67e4b9c1164/tests/integration/test_filtering …
=> Try and fix test_filtering flaky test

labelbox/schema/project.py
There is a limit of 100k data rows that can be checked at once for processing status. Split this call to the backend into chunks of 100k
=> [QQC-2355] Limit number of data rows to check for processing status at once

labelbox/client.py, labelbox/orm/query.py, labelbox/schema/project.py, labelbox/schema/quality_mode.py, tests/integration/conftest.py, tests/integration/test_legacy_project.py, tests/integration/test_project.py
* Removes the `auto_audit_percentage` and `auto_audit_number_of_labels` parameters from `labelbox.client.Client.create_project` and replaces them with the `quality_mode` enum
=> [QQC-2474] Expose quality mode through SDK create_project method

.github/workflows/release-container.yaml, .github/workflows/testing-container.yaml
Adding container images to the Github Container Registry automatically upon pushes to `develop` and on creation of `releases`
=> DEVOPS-1626 - Add Github Action for container release

labelbox/schema/dataset.py
Story: https://labelbox.atlassian.net/browse/SDK-3
=> [SDK-3] Change return of dataset.create_data_rows() to Task

labelbox/client.py, tests/integration/conftest.py, tests/integration/test_data_rows.py
story: https://labelbox.atlassian.net/browse/SDK-246
reusing existing sdk methods to first get the data row id by global key and then get the data row
following existing exception handling paradigm
added sdk integration test and manually tested failure scenarios
NOTE: there is currently no way in the API / ADV to get a data row by global key directly
=> Add sdk method to get data row by global key

labelbox/client.py
@mihhail-m your original proposal was to 
>either would be nice to provide documentation on expected behaviour or check for None values implemented.
We went with updated documentation, here is a rationale I have provided to Kevin:
>When we call client.get_feature_schemas(name_contains=None)  , it returns all root feature schemas. For Mihhail this was confusing and he proposes to throw an error if name_contains in None. However, from the api point of view, this name_contains is converted to a search filter. None means do not filter, so they return every root feature node (paginated). I think this behavior is useful to keep, return is paginated, so I propose just to document it instead of throwing an exception if the name_contains parameter is None
PS I will also create a documentation …
=> [SDK-210] Update the docstring for client.get_feature_schemas() to explain better the use of None

labelbox/schema/data_row_metadata.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_mea_prediction_import.py, tests/integration/conftest.py, tests/integration/export_v2/test_export_video.py
Story: https://labelbox.atlassian.net/browse/SDK-35
Update mea upload tests to use valid annotations and add finer-grain error checking
=> [SDK-35] Improve mea tests

.yapfignore, labelbox/schema/annotation_import.py, labelbox/schema/bulk_import_request.py, mypy.ini, requirements.txt, setup.py
Story: https://labelbox.atlassian.net/browse/SDK-302
The backoff library we use is old and it conflicts with the version the lightning-ai library used by Ancestry
Upon further inspection, I have discovered this library can be replaced with  google.api_core.retry we use elsewhere in our code
This will execute exponential backoff for 2 minutes (default), like
```
tests/integration/annotation_import/test_bulk_import_request.py::test_wait_till_done 
Refreshing... at datetime:  18:57:24
Refreshing... at datetime:  18:57:26
Refreshing... at datetime:  18:57:29
Refreshing... at datetime:  18:57:32
Refreshing... at datetime:  18:57:44
Refreshing... at datetime:  18:58:05
...
```
=> [SDK-302] Remove backoff library

labelbox/schema/batch.py, labelbox/schema/dataset.py, labelbox/schema/model_run.py, labelbox/schema/project.py
https://labelbox.atlassian.net/browse/SDK-300
=> Add exports v1 deprecation warning

tests/integration/test_data_rows.py
This method is not supported by ADV
Depending on when the data platform team fixes this method, I may replace some of the synchronous data row creation calls with asynchronous data row creation in a follow-up PR.
=> Temporarily skip create_data_rows_sync tests

tests/data/annotation_types/data/test_text.py, tests/integration/test_data_rows.py
- Use document from a test bucker for a test failing on codefresh
- Use create_data_rows instead of create_data_rows_sync for a test failing due to ADV
=> Add various sdk test improvements:

labelbox/schema/batch.py, tests/integration/test_batch.py
SDK story: https://labelbox.atlassian.net/browse/SDK-406
Incorrect handling of the member variable `failed_data_row_ids` in the `Batch` class results in the failure of the `_create_batch_async` method. This issue becomes evident when using the `create_batch` method for more than 1,000 data rows. This problem impacts not only Airbnb but also any other client using this SDK call for a larger volume of data rows exceeding 1,000.
=> Fix instantiation of failed_data_row_ids in Batch

Makefile, labelbox/data/annotation_types/video.py, labelbox/data/serialization/ndjson/objects.py, tests/data/annotation_types/test_video.py, tests/data/serialization/ndjson/test_dicom.py, tests/integration/annotation_import/test_data_types.py
Make support for video mask to be provided as a byte string in addition to URL
=> add support for image bytes as a source for raster video mask import

labelbox/schema/export_task.py
`client` is not necessary as it can be obtained from the Task itself.
=> [SDK-425] Remove unnecessary `client` argument from ExportTask methods

labelbox/schema/export_task.py
Added missing fields `organization` and `created_by` that were missing in the ExportTask class.
=> [SDK-426] Add missing fields to ExportTask

labelbox/schema/model_run.py
Remove SQL query from this particular error state, since it doesn't help the user and exposes our query and schema.
=> Remove stack trace and sql query from error message.

labelbox/schema/foundry/app.py, labelbox/schema/foundry/foundry_client.py, tests/integration/test_foundry.py
A required ontology_id field has been added to model app, use this for running foundry jobs.
=> [AL-7584] Add ontology_id for model app

labelbox/data/annotation_types/__init__.py, labelbox/data/annotation_types/data/__init__.py, labelbox/data/annotation_types/data/llm_prompt_creation.py, labelbox/data/annotation_types/data/llm_prompt_response_creation.py, labelbox/data/annotation_types/data/llm_response_creation.py, labelbox/data/annotation_types/label.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/fixtures/export_v2.py, tests/integration/annotation_import/test_data_types.py
It should be possible to run the code below to import pre-labels and ground truth
```python
import sys
import labelbox as lb
import labelbox.types as lb_types
import uuid
API_KEY=""
client = lb.Client(API_KEY, "http://localhost:8080/_gql")
prompt_annotation = lb_types.ClassificationAnnotation(
name="Provide a prompt",
value=lb_types.Text(answer="This is a MAL prompt 2"),
)
label = []
label.append(
lb_types.Label(
data=lb_types.LlmPromptCreationData(
global_key="af3d406e-155f-451b-b828-a6f4744f2e2b"
),
annotations=[
prompt_annotation,
]
)
)
upload_job_mal = lb.MALPredictionImport.create_from_objects(
client = client, 
project_id = "clptvgpf70193v2vu3xb02grt", 
name="mal_import_job_llm_data_gen"+str(uuid.uuid4()), 
predictions=label)
upload_job_mal.wait_until_done()
upload_job = …
```
=> [PTDT-1867] Add llm data gen label types

labelbox/schema/task.py
Did a different PR off a fork for this change doing it off the main repo
=> modified wait till done method

labelbox/schema/foundry/app.py, labelbox/schema/foundry/foundry_client.py
There is a bug I noticed with one of my notebooks. On the run_foundry_app, it is giving me a traceback. I looked through the methods, and it looks like when it creates the APP item with the response for the Pydantic base model, it expects str for the description, but if it is blank, the response actually gives a None object. I made a minor change that makes that field optional with a default value of None, and it works
=> fixed minor bug with foundry run_foundry_app method

.github/workflows/publish.yaml
Username / password not returns http 403
=> Update PyPi Publish action to use trusted publisher setup

labelbox/schema/slice.py
Story: https://labelbox.atlassian.net/browse/SDK-507
API PR: https://github.com/Labelbox/intelligence/pull/18762
Added a new method to get CatalogSlice data rowids AND global keys
NOTE: sdk integration tests are not possible, since we can not create a CatalogSlice via the sdk (see, more example, a slack discussion here for more info https://labelbox.slack.com/archives/C06D281RFT3/p1704495848657209)
=> [SDK-507] Add method to CatalogSlice to get data row identifiers (both uids and global keys)

examples/basics/projects.ipynb
The task wanted this added to the basic/data_row.ipynb notebook but this is a project method. I put it in the project notebook, and it seems to fit better. I had to modify it to import labels since it does not work unless data rows are labeled but this showed off a few of our other project methods in the process. Let me know if this will work!
=> [SN-100] Update notebook for Project move_data_rows_to_task_queue

tests/integration/test_global_keys.py
We are removing global key sanitization from ADV and as a first step I'm removing this associated test case.
=> [DP-335] remove test case checking global key sanitization

labelbox/client.py, labelbox/schema/slice.py
Story: https://labelbox.atlassian.net/browse/SDK-508
Matching API PR: https://github.com/Labelbox/intelligence/pull/18957
=> [SDK-508] Update ModelSlice: fix get_data_row_ids and add get_data_row_identifiers

labelbox/schema/data_row.py, labelbox/schema/dataset.py, labelbox/schema/model_run.py, labelbox/schema/project.py, labelbox/schema/slice.py
The `streamable` parameter was added to the `export_v2` methods to make the existing code reusable by the new `export` methods. While the default value is `False`, setting it to `True` may pose issues as the returned object `Task` doesn't support the actual result that is generated.
=> [SDK-519] Remove `streamable` param from export_v2 methods

labelbox/schema/project.py, tests/integration/test_project.py
Adds a new method `get_label_count` to the Project class, which allows to effectively find how many labels are in the project. Our customers would do this before:
```python
labels_from_labelbox = sum([1 for _ in target_project.labels()])
```
=> [QQC-2962] Add a method to get label count for project

labelbox/schema/slice.py
I want to bring to attention the recent updates made to the SDK's ModelSlice methods, specifically `get_data_row_identifiers` and `get_data_row_ids`. We've modified these methods to now require a model run id as a parameter. It's important to note that these changes are **NOT backward-compatible**.
Prior to the last SDK release (version 3.61.0), these methods were non-functional. After the release of 3.61.0, they have not been operating correctly. This update, involving the inclusion of a model run id, is essentially a fix to ensure these methods work as intended.
While this change does break backward compatibility, it is necessary to correct the functionality that was previously either broken or incorrect.
Required API PR: https://github.com/Labelbox/intelligence/pull/19099
=> [SDK-546] Must pass model run id in order for model slices to work correctly

labelbox/data/annotation_types/annotation.py, labelbox/data/annotation_types/classification/classification.py, labelbox/data/annotation_types/video.py, labelbox/data/mixins.py, labelbox/data/serialization/ndjson/classification.py, labelbox/data/serialization/ndjson/objects.py, labelbox/exceptions.py, tests/data/annotation_types/classification/test_classification.py, tests/data/assets/ndjson/classification_import.json, tests/data/assets/ndjson/classification_import_global_key.json, tests/data/assets/ndjson/classification_import_name_only.json, tests/data/assets/ndjson/conversation_entity_import.json, tests/data/assets/ndjson/conversation_entity_import_global_key.json, tests/data/assets/ndjson/image_import.json, tests/data/assets/ndjson/image_import_global_key.json, tests/data/assets/ndjson/image_import_name_only.json, tests/data/assets/ndjson/nested_import.json, tests/data/assets/ndjson/nested_import_name_only.json, tests/data/assets/ndjson/pdf_import.json, tests/data/assets/ndjson/pdf_import_global_key.json, tests/data/assets/ndjson/pdf_import_name_only.json, tests/data/assets/ndjson/polyline_import.json, tests/data/assets/ndjson/polyline_import_global_key.json, tests/data/assets/ndjson/text_entity_import.json, tests/data/assets/ndjson/text_entity_import_global_key.json, tests/data/serialization/ndjson/test_image.py, tests/integration/annotation_import/conftest.py, tests/integration/annotation_import/test_mea_prediction_import.py
Adds "customMetrics" field definition for ndjson and "custom_metrics" for class object for annotations.
It's meant to be used at the prediction level in when adding predictions to MEA.
Should not be merged without respective changes deployed to rest of tech stack.
=> [AL-7738] Support custom metrics for predictions

labelbox/schema/export_params.py, labelbox/schema/model_run.py
Story: https://labelbox.atlassian.net/browse/PLT-74
Fixing a missing exporter option in the sdk
=> [PLT-74] Add model_run_details to export params to support splits etc.

.github/workflows/publish.yaml
Based on security best practice - I split up the build and publish process so that the `      id-token: write` is available in the minimum amount of steps. 
Also added environment so the publish to pypi portion so we can add further security later. Removed twine install because it was no longer needed.
=> DEVOPS-2168 - Securing GHA Publish to pypi

labelbox/schema/data_row.py, tests/integration/test_data_rows.py
None of these fields should be set to an empty value, and at least 1 is needed for an update.
=> [PLT-130] Validate "external_id", "global_key", "row_data" fields in row update

examples/model_experiments/model_diagnostics/custom_metrics_basics.ipynb
-  updated the iuo in the methods name, since this is a reserved name. 
-  removed hardcoded variables
=> few fixes to custom basics

CHANGELOG.md, docs/source/conf.py, labelbox/__init__.py
Rereleasing 3.64, with an updated changelog.
=> Preparing for 3.65.0 release

labelbox/schema/asset_attachment.py
Adding `CAMERA_IMAGE` attachments which will be used by the experimental point cloud editor (for client demos). For that reason, I didn't add `CAMERA_IMAGE` to any docstrings.
The attachment's value has the following format:
```
{
url: string; // image URL
instrinsic_matrix: number[]; // 3x3 matrix
instrinsic_matrix: number[]; // 4x4 matrix
}
```
Related api / app support: https://github.com/Labelbox/intelligence/pull/19844
=> [CCV-3976] Support for CAMERA_IMAGE attachments in SDK

labelbox/schema/annotation_import.py, tests/integration/annotation_import/test_bulk_import_request.py, tests/integration/conftest.py
Enables a limit of 5000 labels per data row in a single import.
Docs warn users to expect degraded performance at over 5000 labels in a single data row (https://docs.labelbox.com/docs/limits). Users can still get over this limit with multiple imports or manual labelling, but this adds some friction to users getting themselves into this degraded state.
Slack thread for more context: **https://labelbox.slack.com/archives/CRS4VKNR5/p1703025671716839**
=> [PLT-72] Add check for 5000 labels per annotation per data row.

labelbox/client.py
Saw this in one of our issues https://github.com/Labelbox/labelbox-python/issues/1149. I don't see why it is listed as List[Projects] or List[Dataset]. I tried running methods with criteria for one dataset or project, and it was just a paginated collection this also matches our docs.
=> updated type hinting of get_projects and get_datasets to return PaginatedCollections

labelbox/schema/asset_attachment.py, tests/integration/test_data_rows.py
Add the ability to update data row attachments.
Also introduced the `attachment_name` attribute.
=> [PLT-431] add update method to attachments
